### ISSUE TITLE
QEOMResult needs docs and other minor issues

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#1019]
In regards of the newly updated [QEOMResult](https://github.com/Qiskit/qiskit-nature/blob/00d85e3fcca3c405dbe8fd8027784ad2fbca3971/qiskit_nature/second_q/algorithms/excited_states_solvers/qeom.py#L916) 

1. What was all getter/setters before in the result many have been changed to public instance vars but there are no docs for these - consider using `Attributes` to document these. With getter/setters the type could be different - maybe the None aspect is really invalid so when this is documented, although the type now says | None, maybe this should not be exposed. I don't think setting any of these to None is really valid right, we would expect them all to be set. 

2. A public instance field `eigenvalues` has been added yet the parent EigensolverResult has this already and I think that should be used given its the same name.

3. In terms of some of the old setters (W, Q...) being deprecated. If code is still using these - presumably some other QEOM implementation building a result, it will not set S or H so will the result be valid - well S and H will end up being None so it will look like the older result. If these new fields are not being read then it will not be an issue I guess - it would only be the case where its being setup the old way but read by new code that now expects S and H to be set. I guess there is no easy way around this. Maybe we should add some documentation that explains things - though most users I think are going to just be reading the result not  creating one. In terms of the deprecation messages maybe the docs will help as they are at present for the setters they say something like `The W matrix is now computed from the S matrix` which may imply you should be setting S now but the messages could be more prescriptive e.g. `You should now set the S matrix from which W will be computed`. But maybe things will be clearer overall if this transition over to H and S is mentioned in some docs.

**Comment by Anthony-Gandon** [comment]
I can work on that

**Comment by mrossinek** [comment]
Thanks, Anthony!

A few more aspects to consider:
- [ ] Anthony noticed that (while the w,q.. matrices are deprecated) we did not deprecate the corresponding `*_std` properties
- [ ] about Steve's comment on the deprecation: indeed we can improve the deprecation messages. Plus we can also add a `logging.warning` inside of the w, q, ... setters which informs a user that setting these matrices will *not* update H and S to match. This is probably the simplest solution. Plus we can improve the docstrings in this regard :+1:

**Comment by Anthony-Gandon** [comment]
Hi @woodsp-ibm, I'm currently preparing a PR for this issue. 
I was wondering if you could reformulate this comment

> What was all getter/setters before in the result many have been changed to public instance vars but there are no docs for these - consider using Attributes to document these. With getter/setters the type could be different - maybe the None aspect is really invalid so when this is documented, although the type now says | None, maybe this should not be exposed. I don't think setting any of these to None is really valid right, we would expect them all to be set.


I understand that either:

1. I should not have exposed all these attributes and rollback to setters and getters
2. I should change the typing of the current public attributes so that the types None are not exposed.

Many thanks

**Comment by woodsp-ibm** [comment]
> I was wondering if you could reformulate this comment

I'll try... We need the result properly documented so that fields a user can access are listed. Presently the public vars  are not part of the docs, only the getter/setters. As we have it a lot fields are setup with None - though from an actual result perspective, in most cases, we would not want the field left that way such that a user might validly expect None when reading it. Also from a dev perspective we would not want some creator of a new algo to not setup some fields in the result that ought to be there. The code as-is does not really facilitate this (which is part of the reason we have talked about improving result classes). As to getter/setters, or public instance vars documented via Attributes:, either seems ok to me, just wanted to note to be careful around None. Does that help any?
