### ISSUE TITLE
```generate_fermionic_excitations``` produces incorrect output with ```perserve_spin=False``` and unequal alpha and beta spins.

### ISSUE THREAD

**Issue by LSticher** [Qiskit/qiskit-nature#1071]
### Environment

- **Qiskit Nature version**: 0.5.0
- **Python version**: 3.8.15
- **Operating system**: Debian 9.13

### What is happening?

The standard ordering for N spatial orbitals should be that the first N orbitals correspond to spin up and the second N orbitals correspond to spin down. When ```perserve_spin=False``` is used and an unequal number of alpha and beta spins is specified via ```num_particles```, ```generate_fermionic_excitations``` produces incorrect output/output that is inconsistent with the standard ordering of the spin orbitals.

### How can we reproduce the issue?

```python
>>> from qiskit_nature.second_q.circuit.library.ansatzes.utils import generate_fermionic_excitations

>>> generate_fermionic_excitations(num_excitations=1, num_spatial_orbitals=3, num_particles=(2,0), preserve_spin=False)
[((0,), (1,)), ((0,), (2,)), ((0,), (4,)), ((0,), (5,)), ((3,), (1,)), ((3,), (2,)), ((3,), (4,)), ((3,), (5,))]

```

### What should happen?

Instead of generating excitations from the "0" and "3" orbitals, it should instead generate excitations from the "0" and "1" orbitals. Cf. output when ```preserve_spin=True```:

```python
>>> from qiskit_nature.second_q.circuit.library.ansatzes.utils import generate_fermionic_excitations

>>> generate_fermionic_excitations(num_excitations=1, num_spatial_orbitals=3, num_particles=(2,0), preserve_spin=True)
[((0,), (2,)), ((1,), (2,))]
```

```preserve_spin=False``` should generate output with the same occupied orbitals "0" and "1" but excitations to more unoccupied orbitals.

### Any suggestions?

This seems to be an issue with how ```generate_fermionic_excitations``` handles ```preserve_spin=False``` https://github.com/Qiskit/qiskit-nature/blob/e8befeb518f53069a5a784a22968c1b3e1abd09b/qiskit_nature/second_q/circuit/library/ansatzes/utils/fermionic_excitation_generator.py#L198-L227
This interleaving business only works if the number of alpha and beta spins specified in ```num_particles``` are equal. This code treats ```num_particles=(2,0)``` and ```num_particles=(1,1)``` exactly the same as it only involves ```sum(num_particles)```

**Comment by mrossinek** [comment]
Thank you for raising this issue :+1: 

Would you like to try fixing this yourself? It might take some time before I can find time to work on this.

**Comment by lorenzosticher** [comment]
I'd be happy to give this one a go

**Comment by LSticher** [comment]
I'd be happy to give this one a go
