### ISSUE TITLE
Add version number for README code examples

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-nature#1099]
### What should we add?

While answering [this question](https://stackoverflow.com/questions/75755628/modulenotfounderror-no-module-named-qiskit-chemistry/75766605#75766605) on StackOverflow, I realized that the README code examples didn't work with qiskit-nature 0.5.2. I thought there were mistakes in the code, but it turns out the code example was only updated yesterday by https://github.com/Qiskit/qiskit-nature/pull/1084 to work with `main` branch or the future `0.6.0` release. 

I personally like the README code example because it contains all the code necessary for a standard workflow within one code block. But I want to suggest to add a note to users that this code example works with the `main` branch, if people want to see the corresponding code examples for stable releases, go to https://github.com/Qiskit/qiskit-nature/tree/stable/0.5

**Comment by woodsp-ibm** [comment]
We [did have this at one point when code in main was refactored ](https://github.com/Qiskit/qiskit-nature/blob/8795f7cc65610cb77818c3562ab6da1f96d52a25/README.md) and it no longer worked against stable. A disclaimer and a link above the example to the latest stable version. This was removed when we released so it did not end up on the stable version - it seems we did not add something back again for the latest refactor and to link over to stable. We did discuss things - one alternative was to delay the change until release but we rather preferred it doing things as they would be done now - pros and cons - hence before we added the disclaimer & link.
