### ISSUE TITLE
Increase coverage of Qiskit Nature by tutorials

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#111]
There are aspects of Qiskit Nature that are not covered by the present set of tutorials. It would be good to expand the coverage of the function. Here are areas that come to mind

* The new operators and how to use them
* AdaptVQE tutorial
* One on UCC ansatz showing examples of how to set up/use
* Transformers such as active space and freezecore
* Some on drivers (I had done some which were in community tutorials on using the driver, how to save/load for the HDF5 driver etc that can be re-purposed for here)
* Maybe something that shows/includes dipoles in some dissoc plot

**Comment by pbark** [comment]
I converted this issue to an epic, so that we can start populating with the different tutorials and issues for the planning of the upcoming release.
