### ISSUE TITLE
Migrate `EvolvedOperatorAnsatz` and `StarAlgebraMixin` to Terra

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#117]
The evolved_operator_ansatz  is a generic ansatz based on evolution of opflow operators. As such it would make more sense to have this in Terra, as part of the core circuit library, as it has potential for broader use

https://github.com/Qiskit/qiskit-nature/blob/master/qiskit_nature/circuit/library/ansatzes/evolved_operator_ansatz.py

Update: I noticed now the StarAlgebraMixin which I think is also intended to be moved across so I added this here.

https://github.com/Qiskit/qiskit-nature/blob/master/qiskit_nature/operators/second_quantization/star_algebra.py

**Comment by mrossinek** [comment]
I agree that this sounds like a good idea!

@ikkoham I remember you had brought this up for `StarAlgebraMixin` back when you started working on this. Could you take care of this?

@Cryoris Shall we do this in a single PR or would you like to migrate `EvolvedOperatorAnsatz` separately?

**Comment by Cryoris** [comment]
I think 2 might be better since these aren't really related and it keeps the history cleaner. I can take care of the `EvolvedOperatorAnsatz`.

**Comment by ikkoham** [comment]
For `StarAlgebraMixin`, we need to dicsuss whether we should adopt [qargs](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/quantum_info/operators/mixins/group.py#L116) or [permutation](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/opflow/operator_base.py#L580).

**Comment by mrossinek** [comment]
Based on what did we go with `permutation` before?

If the reason for the above is not (or no longer) valid/applicable, I agree that we should adopt the current way of how things are done in Terra :+1:

**Comment by mrossinek** [comment]
Thanks @Cryoris for getting started on this!

@ikkoham could you tackle the `StarAlgebraMixin` within the next week, too?

**Comment by ikkoham** [comment]
got it.

**Comment by mrossinek** [comment]
Migration complete :tada: 

Now we need to deprecate the migrated classes here in Terra :+1:

**Comment by mrossinek** [comment]
Since @ikkoham's part is merged now, I leave @Cryoris assigned to this issue. We had some pointers in #210 with regards to the `EvolvedOpAnsatz` but it appears as though it needs some extra care.
Can you take a look at this before the end of the month?
