### ISSUE TITLE
Conversion of a `SpinOp` object to matrix

### ISSUE THREAD

**Issue by spiccinelli** [Qiskit/qiskit-nature#1187]
### Environment

- **Qiskit Nature version**: 0.6.1
- **Python version**: 3.11.3
- **Operating system**: macOS Ventura 13.3.1

### What is happening?

Conversion of a ```SpinOp``` object to matrix via ```to_matrix()``` throws an error for a number of sites $n>1$.

### How can we reproduce the issue?

```
from qiskit_nature.second_q.operators import SpinOp

op = SpinOp({"X_0 X_1": 1, "Y_0 Y_1": 1, "Z_0 Z_1": 1}, spin=1/2)
print(op)
print(op.to_matrix())
```

### What should happen?

The method ```to_matrix()``` should return the matrix for ```SpinOp```. 

### Any suggestions?

Dimension of ```final_matrix``` are ```(self.num_spins ** dim, self.num_spins ** dim)``` and ```dense_matrix_per_idx = [matrix_per_idx.get(i, i_mat) for i in range(len(self))]``` to ```dense_matrix_per_idx = [matrix_per_idx.get(i, i_mat) for i in range(self.num_spins)]```

**Comment by mrossinek** [comment]
Nice catch, thanks for reporting this!

I think I have a fix working locally and will open a PR soon :+1:
