### ISSUE TITLE
Jordan-Wigner Mapper

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#12]
Migrated from Enterprise Github.
Creator: @mrossinek

### What is the expected behavior?

Implement and test the `JordanWignerMapper`.
This issue breaks-out of #18 and can be used to assign and discuss JW-related topics.

- [x] Implementation
- [x] Unittest
- [ ] Documentation

**Comment by mrossinek** [comment]
Mostly addressed in #60. Documentation will need to be checked for the whole repo before the release anyways.
