### ISSUE TITLE
Refactor `AdaptVQE` to leverage opflow gradients

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#123]
### What is the expected enhancement?

The adaptive VQE was originally implemented in Qiskit Aqua as the outcome of the Qiskit Hackathon Europe 2019, [link](https://github.com/Qiskit/qiskit-aqua/pull/685). Since then, it has already been refactored multiple times during the migration to the `GroundStateEigensolver` interface and later transition to Qiskit Nature.

As it stands today, it still performs the gradient computation manually, see [here](https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/algorithms/ground_state_solvers/adapt_vqe.py#L78), instead of leveraging Qiskit Terra's [gradient functionality](https://github.com/Qiskit/qiskit-terra/pull/5181) released as part of Terra 0.17.0

The goal of this issue, is to refactor the implementation of `AdaptVQE` to make use of the native gradient functionality included in Qiskit Terra.

**Comment by fs1132429** [comment]
👍
