### ISSUE TITLE
FermionicOp gives unwanted ValueError when initialized with list of sparse labels

### ISSUE THREAD

**Issue by LaurinFischer** [Qiskit/qiskit-nature#128]
### Information

- **Qiskit Nature version**: 0.1.0
- **Python version**: 3.9.2
- **Operating system**: Windows 10

### What is the current behavior?
When initializing a `FermionicOp` from a list of sparse labels, which all have indices in ascending order themselves, a `ValueError` is still being raised.  

### Steps to reproduce the problem
```op = FermionicOp([('+_0 -_1', 1.), ('-_0 +_1', -1.)], register_length = 2)```
gives 
```ValueError: Indices of labels must be in ascending order ```

### What is the expected behavior?
No error should be raised.

### Suggested solutions
When checking for ascending indices, this should be done individually for each term in the given list of sparse labels.

**Comment by ikkoham** [comment]
Thank you for your report of the bug.
The work around until next release is
```
FermionicOp('+_0 -_1', register_length=2) - FermionicOp('-_0 +_1', register_length = 2)
```
or 
```
sum(coeff * FermionicOp(label, register_length = 2) for label, coeff in [('+_0 -_1', 1.), ('-_0 +_1', -1.)])
```

I'm sorry for the inconvenience..

**Comment by LaurinFischer** [comment]
Thanks for the workarounds, these work great. 👍 And no worries!
