### ISSUE TITLE
Naming and packaging fixes

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#13]
Migrated from Enterprise Github.
Creator: @mrossinek

#### Naming
In the remainder of Qiskit we are consistently using verbs for class names, rather than nouns.
Thus, we should follow that approach and rename the classes and modules like:
- [x] `Mapping` -> `Mapper`
- [x] `Transformation` -> `Transformer`
etc.

#### Location
Currently, we plan a differentiation between first and second quantization in the `problems`, `operator` and `transformer` modules. However, the `mappers` also require this differentiation because (at least the currently existing ones) only work in that regime. Thus, we should move all current `mappers`:
- [x] `qiskit_nature.mappers.*` -> `qiskit_nature.mappers.second_quantization`

**Comment by mrossinek** [comment]
Closed by #60.
