### ISSUE TITLE
Add problems.second_quantization.{molecular,lattice,etc.} interfaces and implementations

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#14]
Migrated from Enterprise Github.
Creator: @mrossinek

Since the latest release of Qiskit Aqua we have the `FermionicTransformation` (and alike) classes which can be used to quickly map from a problem description (i.e. a driver) to a qubit operator.
With the refactored input flow we want to be able to do something similar but we will call it slightly differently.

As an example I here propose a `ProblemTranslation`. We need to do the following things for it:
- [ ] design its general interface: `ProblemTranslation`
  - likely it will map from a `Driver` to a `PauliSumOp`
  - it will need to be able to apply mappings and transformations
- add basic implementations for the cases:
  - [ ] fermionic
  - [ ] bosonic
  - [ ] (optionally:) spin [possibly related to Simon and Giulia's lattice models]

**Comment by manoelmarques** [comment]
Creator: @mrossinek

Here is a short snippet on an example workflow for a molecular problem in second quantization:
```python
# initialize driver outside of the class
driver = FermionicDriver(molecule, basis, etc.)

# then use the following method to get a qubit op for the problem described by this driver
def get_qubit_op(driver):
    # run the driver
    second_q_op = driver.run()

    # apply optional transformations
    trafos = [ActiveSpaceTransformation(...), ParticleHoleTransformation(...)]
    for t in trafos:
        second_q_op = t.transform(second_q_op)

    # map to qubit op
    qubit_op = ParityMapping(...).map(second_q_op)

    return qubit_op
```

**Comment by mrossinek** [comment]
I am closing this in favor of the individual issues to keep track of the separate problem instances:
- Molecular: #42 
- Lattice models: #43 
- Vibrational structure: #44
