### ISSUE TITLE
Adapt bosonic drivers to the new input flow

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#15]
Migrated from Enterprise Github.
Creator: @mrossinek

All bosonic drivers need to be adapted to produce a `SecondQuantizedSumOp` rather than a `QMolecule`. Be sure to also take a look at #14 for examples of the fermionic driver.

- [ ] GaussianForcesDriver

We also need to figure out a good place for the following classes:
- [ ] WatsonHamiltonian
- [ ] BosonicBasis
  - [ ] HarmonicBasis

**Comment by mrossinek** [comment]
Disclaimer: parts of the above comment are outdated. New information on how the drivers need to be adapted will follow in the near future.

**Comment by mrossinek** [comment]
As explained in #5 we will leave the drivers mostly unchanged for now. We can re-open this once needed.
