### ISSUE TITLE
FermionicTransformation is still found in code docstrings

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#159]
In vqe_ucc_factory it appears in docstrings which end up as user API ref. docs/

https://github.com/Qiskit/qiskit-nature/blob/48ede57feb36c720f576f390e77bab0eb367c470/qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py#L171-L172

https://github.com/Qiskit/qiskit-nature/blob/48ede57feb36c720f576f390e77bab0eb367c470/qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py#L180-L181

In qeom.py its less problematic since its just a comment in the code, but ideally should be addressed too

https://github.com/Qiskit/qiskit-nature/blob/48ede57feb36c720f576f390e77bab0eb367c470/qiskit_nature/algorithms/excited_states_solvers/qeom.py#L208-L209

**Comment by mrossinek** [comment]
@woodsp-ibm I talked to Alex (@Durd3nT) who is willing to help on this. #307 seems a little bit more involved so maybe you can look at that one instead?
