### ISSUE TITLE
Adapt fermionic drivers to the new input flow

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#16]
Migrated from Enterprise Github.
Creator: @mrossinek

All fermionic drivers need to be adapted to produce a `SecondQuantizedSumOp` rather than a `QMolecule`. As a good starting point, the following may be helpful to transform what is currently stored in a `QMolecule` into a `FermionicSumOp`:

```python
base_ops = []

one_body_ints = qmol.one_body_integrals
for idx in itertools.product(range(len(one_body_ints)), repeat=2):
    coeff = one_body_ints[idx]
    if not coeff:
        continue
    label = ['I'] * len(one_body_ints)
    base_op = FermionicOperator(label, coeff=coeff)
    for i, op in [(idx[0], '+'), (idx[1], '-')]:
        label_i = label.copy()
        label_i[i] = op
        base_op *= FermionicOperator(''.join(label_i))
    base_ops.append(base_op)

two_body_ints = qmol.two_body_integrals
for idx in itertools.product(range(len(two_body_ints)), repeat=4):
    coeff = two_body_ints[idx]
    if not coeff:
        continue
    label = ['I'] * len(two_body_ints)
    base_op = FermionicOperator(label, coeff=coeff)
    # mind the chemists' notation of the two-electron integrals!
    for i, op in [(idx[0], '+'), (idx[2], '+'), (idx[3], '-'), (idx[1], '-')]:
        label_i = label.copy()
        label_i[i] = op
        base_op *= FermionicOperator(''.join(label_i))
    base_ops.append(base_op)

fer_op = FermionicSumOp(base_ops)
```

- [ ] CP2KDriver
- [ ] FCIDumpDriver
- [ ] GaussianDriver
- [ ] HDF5Driver
- [ ] Psi4Driver
- [ ] PyQuanteDriver
- [ ] PySCFDriver

**Comment by manoelmarques** [comment]
Creator: @mrossinek

Some thought on the above snippet:

- we should generalize this to also work for `n`-body terms (like Mario Motta did recently in this PR: https://github.com/Qiskit/qiskit-aqua/pull/1483)
- the above may be easier if we use the physicist' notation for the integrals/coefficients
- we should probably implement the above as a utility method in the `FermionicOperator` class
- if we do so, we can do the transformation to physicist' notation internally (and allow the user to disable it through a `kwarg`)

**Comment by mrossinek** [comment]
Disclaimer: some of the above comments are outdated. New information on how the drivers need to be adapted will follow in the near future.

**Comment by mrossinek** [comment]
As explained in #5 we will leave the drivers mostly unchanged for now. We can re-open this once needed.
