### ISSUE TITLE
Ensure compatibility with Sphinx 4

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#188]
### What is the expected enhancement?

Sphinx 4 introduced some new warnings which caused or CI to fail once it was able to upgrade Sphinx to this version.
Some of our dependencies still rely on Sphinx < 4 which is why #187 pins the version anyways.

Nonetheless, this issue should be used to track the progress on resolving all warnings raised by the new Sphinx version.

**Comment by woodsp-ibm** [comment]
I just built the html using the latest Sphinx 4.0.2 and it built more or less fine, just one problem mentioned below, not a whole bunch of warnings as had been seen/reported. (FYI sphinx-panels, that we now depend on, though its pinned for < 4, works with 4 ok - there is a PR in fact for it to change the pinning but its not been released yet). Now this is building whatever is current in main branch at this time. I dropped back to 4.0.0, to double check things, and I see a whole bunch of warnings so I am assuming that it was some bug that was fixed related to Sphinx.

Now there is a single warning about `BopesSampler` It seems we document it in two init files, 
 
 * qiskit_nature/algorithms/pes_samplers/__init__.py
 * qiskit_nature/algorithms/__init__.py
 
where we should probably just pick one. If algorithms seems like the right place then expose it there via the docs. Locally, just to see, I removed it from the pes_samplers init file and no longer saw any warning for it.
