### ISSUE TITLE
Extract common functionality into the interfaces

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#19]
Migrated from Enterprise Github.
Creator: @mrossinek

- [ ] extract common functionality into the `ParticleOperator`
  - This will probably affect things like `__sub__`, `__rmul__`, `__neg__`, `__pow__`, `__ne__` because all of these can link to their counterpart

- [ ] extract common functionality into the `SumOp` (similar to the above)

**Comment by mrossinek** [comment]
Since we merged the `ParticleOperator` and `SumOp` interfaces, this issue is outdated and can be closed.
