### ISSUE TITLE
Understanding the difference in qubitOp's minimum eigenvalue and qmolecule's hf_energy

### ISSUE THREAD

**Issue by obliviateandsurrender** [Qiskit/qiskit-nature#190]
### Information

- **Qiskit Nature version**: 0.1.2
- **Python version**: 3.8.5
- **Operating system**: Linux Mint

### What is the current behavior?

When I want to make a small molecule, for example say, H<sub>2<sub>, I first build its qmolecule and then its qubitOp:
```
molecule = Molecule(geometry=[['H', [0., 0., -0.741]],
                                                    ['H', [0., 0., 0.0]]],
                                  charge=0, multiplicity=1)
driver = PySCFDriver(molecule = molecule, unit=UnitsType.ANGSTROM, basis='sto3g')
qmolecule = driver.run()
qubitOp = FermionicOperator(h1=qmolecule.one_body_integrals,
                            h2=qmolecule.two_body_integrals).mapping('jordan_wigner')
```
Now, when I compare the eigenvalue of the qubitOp, and the Hartree-Fock energy of the qmolecule, they come out to be different. 

- qubitOp minimum eigenvalue: **-1.851413691521** 
- qmolecule Hartree Fock energy: **-1.1167061373523686**

### What is the expected behavior?

Since qubitOp is just the qubitized transformation for the molecular Hamiltonian of my qmolecule, shouldn't the minimum eigenenergy of the former match with electronic energy (HF) of the latter? If not, then what am I missing on the implementation part or the theoretical part? 

Also, just to mention, I did realize that adding qmolecule's nuclear repulsion energy does reduce the gap between the two values but still, they are not equivalent. 

- GroundStateEigensolver's output
![image](https://user-images.githubusercontent.com/23234279/118128455-89db5680-b418-11eb-98ab-1c5ffb982a86.png)

- Gaussian's output
![image](https://user-images.githubusercontent.com/23234279/118129326-aaf07700-b419-11eb-83f0-41528654f3e6.png)

**Comment by woodsp-ibm** [comment]
The Hartree Fock energy is that of the Hartree Fock state which is an approximation to the solution state but it will be above the true value as its an approximation that does include some aspects of the system. You can find more about the HartreeFock method if you search online.

What we create is an operator whose minimum Eigenvalue is the FCI energy value (Full Configuration Interaction) of the electronic part of the system; the nuclear repulsion part, in essence a constant, needs adding to that value to generate the total ground state energy of the system. As you see from above the total is -1.137 which is a bit lower, as expected, than the HF energy of -1.116. If you use the chemistry program/library natively to compute an fci value you will see that its consistent with the value computed here, 

Does that help?

**Comment by obliviateandsurrender** [comment]
Interesting. I do know about the Hartree-Fock method, but I didn't realize that the operator (qubitOp) created in Qiskit actually corresponds to the FCI value. All of the deviations make complete sense now. Thank you for your prompt response.
