### ISSUE TITLE
Finish the SecondQuantizedOperator implementation

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#20]
Migrated from Enterprise Github.
Creator: @mrossinek

- [ ] unittest all methods

- ~unify the `SecondQuantizedOp` as much as possible with the other classes~
- ~make the `SecondQuantizedSumOp` implement the `SumOp` interface~

**Comment by manoelmarques** [comment]
Creator: @mrossinek

Here is the new UML for the proposed `SecondQuantizedOp`:
![Qiskit_Nature_Operators](https://media.github.ibm.com/user/251930/files/87d14d00-5b34-11eb-9db0-767b38a49052)

**Comment by mrossinek** [comment]
Here is an updated overview of the UML:
![screenshot_1613122875](https://user-images.githubusercontent.com/21973473/107752344-e39b8a00-6d1e-11eb-9198-60a90c7df837.png)
