### ISSUE TITLE
Type error when the wrong number of electrons is used in ActiveSpacetransform

### ISSUE THREAD

**Issue by Ciamar** [Qiskit/qiskit-nature#207]
### Information

- **Qiskit Nature version**: 0.1.3
- **Python version**: 3.8
- **Operating system**: Windows 10 / jupyter notebook

### What is the current behavior?

In ActiveSpaceTransformer, when there is an error in number of electros, instead of raising a QiskitNatueError, there is a type error that appears to be because of a missing int to str conversion

### Steps to reproduce the problem

```
from qiskit_nature.transformers import ActiveSpaceTransformer

from qiskit_nature.drivers import Molecule

molecule = 'Li 0.0 0.0 0.0; H 0.0 0.0 1.5474'
m = Molecule(geometry=molecule)


ast = ActiveSpaceTransformer(3, 6)


ast.transform(m)

```
![image](https://user-images.githubusercontent.com/11468019/119517967-600b2380-bd78-11eb-962c-9586e4bf88b5.png)

### What is the expected behavior?

A QiskitNatureError should appear instead of the type error

**Comment by mrossinek** [comment]
Thanks @Ciamar for finding this! I just opened a PR to fix this :+1:
