### ISSUE TITLE
The order of the auxiliary operators returned from ElectronicStructureProblem.second_q_ops disagrees with doc description.

### ISSUE THREAD

**Issue by HNK-coder** [Qiskit/qiskit-nature#218]
### Information

- **Qiskit Nature version**: latest
- **Python version**: don't care
- **Operating system**: don't care

### What is the current behavior?

The order of the auxiliary operators returned from ElectronicStructureProblem.second_q_ops disagrees with doc description.
The doc says, "
        Returns:
            A list of `SecondQuantizedOp` in the following order: electronic operator,
            total magnetization operator, total angular momentum operator, total particle number
            operator, and (if available) x, y, z dipole operators", 
 whereas, in _create_all_aux_operators , they are actually arranged in the order as
    "aux_second_quantized_ops_list = [
        _create_total_particle_num_op(q_molecule),
        _create_total_ang_momentum_op(q_molecule),
        _create_total_magnetization_op(q_molecule),
    ]".

### Suggested solutions

The doc description should be corrected in accordance with the actual order of the operators returned.

**Comment by mrossinek** [comment]
Hi @HNK-coder, thanks for raising this issue! This was actually recently addressed on the `main` branch by #208.
The online documentation will be updated with the next release.
