### ISSUE TITLE
Search Function not working for Qiskit Nature 

### ISSUE THREAD

**Issue by divshacker** [Qiskit/qiskit-nature#219]
### Information

- **Qiskit Nature version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is the current behavior?
The Search Function of Qiskit Nature is not working.

### Steps to reproduce the problem
Just go to this https://qiskit.org/documentation/nature/ and type anything you want to search.

### What is the expected behavior?
It will not work as expected.

### Suggested solutions
I think search function have some sort of bug internally and needs to be fixed ASAP

**Comment by divshacker** [comment]
Well then I think there is no point in opening this issue now. I am closing this and consider this discussion further on Qiskit/qiskit#1223.

**Comment by mtreinish** [comment]
Fwiw, this issue should be fixed by https://github.com/Qiskit/qiskit_sphinx_theme/pull/34
