### ISSUE TITLE
Possiblly a bug in the README sample

### ISSUE THREAD

**Issue by liwt31** [Qiskit/qiskit-nature#225]
### Information

- **Qiskit Nature version 0.1.3**:
- **Python version 3.7**:
- **Operating system Linux**:

### What is the current behavior?
```
ansatz.compose(init_state, front=True)
```
This line probably does nothing because by default `compose` is not in place as of qiskit version 0.17.4

### Suggested solutions
Change the line to
```
ansatz.compose(init_state, front=True, inplace=True)
```

**Comment by woodsp-ibm** [comment]
That line you indicate indeed has no consequence on the subsequent code. Either the returned circuit needs to be used in VQE or as you suggest use inplace=True to alter the ansatz cct itself.

There is a unit test that checks the outcome of the readme code `test/test_readme_sample.py` that needs to stay in sync with whatever change is done too.

**Comment by shil-m** [comment]
Hi, I am new to contributions but I would like to work on this issue. Can I be assigned?

**Comment by woodsp-ibm** [comment]
Done - thank you for offering to look at this.
