### ISSUE TITLE
Bopes Sampler tutorial has incorrect if tests and output has warnings

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#247]
docs/tutorials/05_Sampling_potential_energy_surfaces.ipynb

line [9]
```
<>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-9-a52335c0e03d>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if condition is not 'np':
```
and similar in ln[12]
```
<>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-12-aea40004e9fe>:6: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if condition is not 'np':
  ```

**Comment by woodsp-ibm** [comment]
In the latest code it is printing this too
```
The measured number of particles 1.998919964515065 does NOT match the expected number of particles 2!
The measured number of particles 2.1923056239385375 does NOT match the expected number of particles 2!
The measured number of particles 2.1306926534684445 does NOT match the expected number of particles 2!
The measured number of particles 2.331470449507494 does NOT match the expected number of particles 2!
The measured number of particles 1.9536592471687682 does NOT match the expected number of particles 2!
The measured number of particles 0.8274093631108661 does NOT match the expected number of particles 2!
The measured number of particles 2.080520198403325 does NOT match the expected number of particles 2!
The measured number of particles 1.7168938121529553 does NOT match the expected number of particles 2!
The measured number of particles 1.9209461627090578 does NOT match the expected number of particles 2!
...
```
which the currently published notebook on stable branch does not do (@mrossinek in case you have any thoughts - in any case I'll look after taking care of issue #242 otherwise that warning ends up in output in the notebook too)

**Comment by mrossinek** [comment]
Thanks for catching this! I will make the relative and absolute tolerances of that check configurable as part of #303 
However, those numbers are **really** far off sometimes. I think what one would have to do is disable that logger:
```python
logging.getLogger("qiskit_nature.properties.second_quantization.electronic.particle_number").setLevel(logging.ERROR)
```

**Comment by mrossinek** [comment]
After talking to @pbark offline, we decided to move this logging call to `info` which should eliminate the problem of unwanted warnings in the tutorials. The fact that this will be logged is documented which should help users who are interested in this information find it :+1:

**Comment by woodsp-ibm** [comment]
We can also think about how to do things like this in regards to the sort of validation of the experiment that has been discussed - around validating input values/configuration etc for the user to better assure their computation is likely to succeed. Here its validating the result against expected values - its the reason it was added of course to allow an end user to see these other properties and make a judgement. Moving it to info logging is fine. I had wondered about some more global flag that would enable such validation checks as this - but maybe thats best left until validation is looked at more comprehensively.

**Comment by mrossinek** [comment]
I absolutely agree! I do want to go back to that discussion of user input validation and improving output awareness.
I also like the idea of some sort of a global switch to turn such checks on/off.

But like you say, let's leave this until we revisit that discussion :+1:
