### ISSUE TITLE
Generalize BaseProblem to capture sampling problems.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-nature#261]
The current `BaseProblem` interface should be renamed to `BaseSecQuantProblem` (or similar) since it contains logic specific to second quantized problems that does not appear in sampling problems.
There is need for a new interface, one level higher, called `BaseProblem` which both `BaseSecQuantProblem`  and `BaseSamplingProblem` would implement. Then, ground state eigensolvers present in Nature should operate on the new `BaseProblem`, not the current one.

**Comment by MartinBeseda** [comment]
Hi @dlasecki ,
can I have a look at this one?

Best,
Martin

**Comment by dlasecki** [comment]
Hello @MartinBeseda, 
After internal discussions we decided to take a different route for now than generalizing the existing BaseProblem class. We still need to figure out some details about it internally. Thanks for offering help though. For now, I'm closing this issue.
