### ISSUE TITLE
Error in docstring of Second Quantization Qubit Mappers

### ISSUE THREAD

**Issue by jsistos** [Qiskit/qiskit-nature#278]
# **Problem**
The documentation for a bunch of the second quantization mappers is not being rendered correctly, as seen in the docs for the [Jordan Wigner](https://qiskit.org/documentation/nature/stubs/qiskit_nature.mappers.second_quantization.JordanWignerMapper.html#qiskit_nature.mappers.second_quantization.JordanWignerMapper) mapper. 

![bugmap](https://user-images.githubusercontent.com/46694558/125883245-3f38dcab-3d50-48d1-91c7-a411f079ac44.png)

# **Origin**
The docstring for these mappers is inherited from [```QubitMapper```](https://github.com/Qiskit/qiskit-nature/blob/fc8a649f3baa594526599ce4d99e034fa64ecbdc/qiskit_nature/mappers/second_quantization/qubit_mapper.py#L27)
```python
class QubitMapper(ABC):
    """The interface for implementing methods which map from a `SecondQuantizedOp` to a
    qubit operator in the form of a `PauliSumOp`.
    """

    def __init__(self, allows_two_qubit_reduction: bool = False):
        """
        Args:
            allows_two_qubit_reduction: Set if mapper will create known symmetry such that the
            number of qubits in the mapped operator can be reduced accordingly.
        """
        self._allows_two_qubit_reduction = allows_two_qubit_reduction

```
which looks almost like what is seen in the docs. Apidoc is misunderstanding the word _number_ as an arg datatype
# **Fix**
To fix this, the appropriate format must be given to ```QubitMapper```'s docstring.

**Comment by woodsp-ibm** [comment]
Thanks for reporting this - the continuation line starting with 'number of...' should have been indented; otherwise as you its treating that as another arg following this one.
