### ISSUE TITLE
Protein Folding API - Lists plus their lengths

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#309]
To follow on the discussion on the main PR #231, in regards of its public API, ahead of the function being released. In particular around passing both a List, which has a length property, as well its length separately - see comments in that PR here https://github.com/Qiskit/qiskit-nature/pull/231#issuecomment-894307986 and  https://github.com/Qiskit/qiskit-nature/pull/231#issuecomment-894320719

In summary the current API looks like this (example in the docs)
```
main_chain_residue_seq = ["S", "A", "A", "S", "S", "A", "S", "A", "A", "G"]
main_chain_len = 10
side_chain_lens = [0, 0, 1, 1, 1, 1, 1, 1, 1, 0]
side_chain_residue_sequences = [None, None, "A", "A", "A", "A", "A", "A", "S", None]

peptide = Peptide(
    main_chain_len, main_chain_residue_seq, side_chain_lens, side_chain_residue_sequences
)
```
where the lengths are passed as well as the lists themselves. Since the lengths can be directly read from the Lists it seems like passing them explicitly is an extra burden on an end user. Rather it seems simpler to pass
```
main_chain_residue_seq = ["S", "A", "A", "S", "S", "A", "S", "A", "A", "G"]
side_chain_residue_sequences = [None, None, "A", "A", "A", "A", "A", "A", "S", None]

peptide = Peptide(
    main_chain_residue_seq, side_chain_residue_sequences
)
```

Also, if a user is entering such sequences manually would not a simple String suffice? I can see if the input is being generated programmatically then a mutable List lends itself to being more easily created/changed that a non-mutable String. If String were supported it would look more like
```
main_chain_residue_seq = "SAASSASAAG"
side_chain_residue_sequences = ["", "", "A", "A", "A", "A", "A", "A", "S", ""]

peptide = Peptide(
    main_chain_residue_seq, side_chain_residue_sequences
)
```
Where I also eliminated None from the interface by allowing an empty string to placed there. In the sidechains a string of max len 1 can be checked since that is all that is supported today. In the future these side strings could grow in length when supported.

Now of course either a List or a String (empty or not) could be supported for more flexibility. In summary though the main conversation, in my mind, is around explicit lengths, with the representation additional since this whole discussion is for me is around ease of use etc.

**Comment by mrossinek** [comment]
I have to agree with @woodsp-ibm here. In fact, I would prefer the string-style definitions over any of the previously discussed/proposed designs. I believe it is the most readable out of the lot and it also has the benefits of:
* being easy to be generated programmatically (you could have a mutable list if you wanted but that is easily joined to a string and I don't think this causes a significant overhead in this scenario)
* it is easy read from an input file (if we ever want to move towards that or if a user has a custom script which reads input from a file themselves)

Furthermore, it also deals with the edge case of an empty side chain natively and is easily extendable towards longer side chains in the future.

**Comment by dlasecki** [comment]
Looks good.
