### ISSUE TITLE
 How to convert the pauli_op to  Hamiltonian matrix in VEQ

### ISSUE THREAD

**Issue by Qiankun-source** [Qiskit/qiskit-nature#311]
### What is the expected enhancement?
In qiskit tutorial: Electronic structure
The final result is pauli_opertor, but obtaining the corresponding  Hamiltonian matrix is important sometimes.
I want to know whether there is a method/model to get this matrix.

Thanks.

**Comment by mrossinek** [comment]
The `QubitConverter` will produce a `PauliSumOp` object. This is an operator which is implemented in Qiskit Terra.
It provides a `to_matrix` method which is documented [here](https://qiskit.org/documentation/stubs/qiskit.opflow.primitive_ops.PauliSumOp.html#qiskit.opflow.primitive_ops.PauliSumOp.to_matrix). You may also be interested in its [sparse variant](https://qiskit.org/documentation/stubs/qiskit.opflow.primitive_ops.PauliSumOp.html#qiskit.opflow.primitive_ops.PauliSumOp.to_spmatrix).

Does this answer your question?

**Comment by mrossinek** [comment]
I assume this question in answered. Please re-open otherwise
