### ISSUE TITLE
Implement the interpret method for protein folding.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-nature#313]
Protein folding problem lacks the implementation of an interpret method for its result. 

The interpret method should be implemented that hopefully makes it easier for the user to decode the meaning of a result, i.e. the shape of a protein. For instance, it could segregate qubits into configuration qubits and interaction qubits. Configuration qubits and their state after optimization could be mapped to a description of the shape of a protein, e.g.:
Turn from main bead {x} in direction {y}.

Another good way of understanding the result is a plotting feature which will be addressed separately in #235.

**Comment by woodsp-ibm** [comment]
Does this take care in some way of what was described in #259 - which I see was just closed but no reason was given. Or was it already taken care of in main protein folding work that was done.

**Comment by dlasecki** [comment]
> Does this take care in some way of what was described in #259 - which I see was just closed but no reason was given. Or was it already taken care of in main protein folding work that was done.

It was taken care of.

**Comment by mrossinek** [comment]
Closed by #655
