### ISSUE TITLE
Add `TwoBodyElectronicIntegrals` notation conversion utilities

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#337]
### What is the expected enhancement?

Currently the `TwoBodyElectronicIntegrals` matrices are expected to be given in chemistry notation. Utility methods to convert to and from the physics notation would be valuable additions to this class.

Analogous to this we may also be interested in utility methods to convert the `SO`-basis matrices of the one- and two-body electronic integrals between the (currently required) blocked and interleaved spin formats.

@jlapeyre: I know that you previously worked on some utility methods for symmetry detection+conversion. Would you be interested in joining efforts to implement this enhancement?

**Comment by mrossinek** [comment]
Here is the [related TODO marker](https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/properties/second_quantization/electronic/integrals/two_body_electronic_integrals.py#L32) in the source code.

**Comment by jlapeyre** [comment]
Yes.

**Comment by mrossinek** [comment]
@jlapeyre do you think you could share you code for this in a draft PR or gist?

**Comment by jlapeyre** [comment]
@mrossinek There are some choices in how to arrange this. Here is one scenario.

* Assume you always want to store the data in chemists' index order.
* Detect the index order upon construction and then convert to chemists' order
* Give a warning, or not, if the input data is in physicists' index order.
* Give a warning, or not, if the input data is in "intermediate" order. I haven't seen this order used intentionally anywhere. But, it is easy enough to get by mistake. Eg. start with chemists' order then do a physicists' to chemists' transformation. The result is "intermediate".  A good option here might be to raise an error if "intermediate" is detected. That is, we require either physicists' or chemists'. If the user is getting data in the wrong form and can't control it, then they can do an explicit transformation. I mean, we should not paper over what is very likely a bug earlier in the workflow; but allow an easy way to get it to work.

**Comment by jlapeyre** [comment]
A pattern that I see in Qiskit is to put some more generally useful functions in a file `xxx_utils.py`. Then call these from class or instance methods. Other people like to put everything inside a class if possible. The problem with the latter is it makes the code unavailable to users who have a workflow that we did not anticipate.
