### ISSUE TITLE
Add support for callback for QEOM

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-nature#376]
### What is the expected enhancement?

This is related to #375

It would be nice to see interim results for excited states calculation iterations using `QEOM` algorithm. Current code only supports `callback` in the ground state calculation.

I think in general, it would be nice to add `callback` kwarg to `GroundStateEigensolver` (refers to `GSE` below) and `ExcitedStateEigensolver` classes. 

If the solver (`VQE`, `VQEUCCFactory`, `NumPyMinimumEigensolverFactory`) given to `GSE` has no callback specified, the callback pass to the solvers from `GSE`. If the solver already has callback specified, the callback pass to `GSE` can overwrite it.

**Comment by HuangJunye** [comment]
See this gist of a notebook for details: https://gist.github.com/HuangJunye/35dbbab66063a71ec5774a4a0079e1b6

**Comment by mrossinek** [comment]
Hi @HuangJunye! Thanks for the suggestion. I believe there are two suggestions here:

### Callback for QEOM
The excited states calculation of QEOM actually has no iterative steps. It performs an initial ground state calculation (which has a callback available after #375) but after that it only evaluates some additional auxiliary operators and performs classical post-processing of these results.
Thus, I don't think a callback is really needed anywhere here.

### Exposing callbacks on the GSE/ESE level
As you outline, this would require handling quite a few cases of whether the VQE already has a callback or not. Thus, I don't think that this adds much additional benefit after we have fixed #375 so I would argue that this is not really needed either.

Do you agree with the above?

**Comment by HuangJunye** [comment]
Thanks for looking into this issue and summarizing our discussions over Slack! I agree with both points. We can close this issue.
