### ISSUE TITLE
VQE Factory method improvements

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#384]
### What is the expected enhancement?

#380 introduces dependencies on private variables of the `VQE` class. This is a temporary workaround until https://github.com/Qiskit/qiskit-terra/issues/7093 gets resolved. This issue is used to keep track of revoking this workaround.

Another possibility would be to construct `self._vqe` freshly every time `get_solver` gets called. But we decided against that.

**Comment by woodsp-ibm** [comment]
As the above Terra PR has been merged it would be possible to do this now so I removed the on hold label.

However I am wondering whether a better approach would be to let the user pass in a VQE instance, that the factory then uses, and have a getter/setter for it like the ansatz. Since the intent seems to be to re-use the vqe/uccsd instances. By passing in a VQE instance the user is free to set it however they like and via the vqe getter can update as they choose. This way the factory does not have to delegate all the setter/getters which has the disadvantage of getting out of sync with VQE if/when it alters its parameters.

**Comment by mrossinek** [comment]
I like this idea of passing in a VQE instance. If we do this, we should arguably deprecate the other getter/setter methods and `__init__` arguments in favor the properties exposed on the `VQE` directly. What do you think?

**Comment by woodsp-ibm** [comment]
Yes, given a getter/setter for VQE the instance is always then available via the factory and it can be changed directly; exposing aspects of VQE, whether via the constructor or properties, I would agree should then be deprecated/removed. I would expect VQE to be changing as these expectation objects are introduced using an directly would allievate trying to keep it in sync. The one things is that the factory is responsible for the ansatz so we might have to note that and when getting the solver ensure that the anstaz is the factory UCC instance maybe just by setting it there such that should the user attempt to do it directly via VQE that would be ignored/overridden by the factory

**Comment by woodsp-ibm** [comment]
One other thought - maybe we should thing about allowing an instance of the VQEClient runtime here too as an alternative to the local running VQE. While UCCSD maybe problematic today on an actual device the runtime can still be used with the remote simulator right.

**Comment by iuliazidaru** [comment]
@mrossinek Thank you for thinking about this issue and providing so many comments here.
Please let me check if I understood correctly what this task is about:
MinimumEigenSolverFatory implementation should create an instance of solver and expose it via minimum_eigensolver method?

If I understand correctly the approach, based on the experience working on #510 I would have some comments.
First the class is called "Factory". In Factory Design Pattern, the factory class is used to create new instances based on given properties. It creates different instances. GroundStateEigensolver uses VQEUCCFactory to create a solver using a specific problem. In the case that the instance is saved inside the factory, the same factory instance cannot be used and the design has to be changed.

**Comment by mrossinek** [comment]
Yes, all of the above is correct. However, I still consider this to be a factory (although not to the full extent), because `MinimumEigensolver` objects from Terra can be constructed piece-by-piece. This means that, although we initialize a solver during the factories `__init__` and store it's reference, this object will not be usable until the factories `get_solver` method populates the remaining required pieces needed by the solver at runtime.

It is true that not the entire object gets created at runtime but the `MinimumEigensolver` only becomes usable at runtime. Does that make sense?

**Comment by iuliazidaru** [comment]
@mrossinek Please assign this task to me too.
