### ISSUE TITLE
`BOPESSampler` does not support `MinimumEigensolverFactories`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#398]
### Information

- **Qiskit Nature version**: cb05d69661a9d467aed9d3f208ea5630f7dc9fbf
- **Python version**: 3.9.7
- **Operating system**: Linux

### What is the current behavior?

```python
Traceback (most recent call last):
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/tmp10.py", line 32, in <module>
    bs = BOPESSampler(VQEUCCFactory)
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/qiskit_nature/algorithms/pes_samplers/bopes_sampler.py", line 95, in __init__
    if isinstance(self._gss.solver, VariationalAlgorithm):  # type: ignore
AttributeError: type object 'VQEUCCFactory' has no attribute 'solver'
```

### Steps to reproduce the problem

```python
from functools import partial

import numpy as np

from qiskit_nature.algorithms.ground_state_solvers.minimum_eigensolver_factories import (
    VQEUCCFactory,
)
from qiskit_nature.algorithms.pes_samplers import BOPESSampler
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.drivers import Molecule
from qiskit_nature.drivers.second_quantization import (
    ElectronicStructureDriverType,
    ElectronicStructureMoleculeDriver,
)
from qiskit_nature.mappers.second_quantization import ParityMapper
from qiskit_nature.problems.second_quantization.electronic import ElectronicStructureProblem

stretch = partial(Molecule.absolute_distance, atom_pair=(0, 1))

molecule = Molecule(
    geometry=[
        ["H", [0.0, 0.0, 0.0]],
        ["H", [0.0, 0.0, 1.0]],
    ],
    degrees_of_freedom=[stretch],
)
driver = ElectronicStructureMoleculeDriver(molecule, "sto3g", ElectronicStructureDriverType.PYSCF)
problem = ElectronicStructureProblem(driver)

converter = QubitConverter(ParityMapper())

bs = BOPESSampler(VQEUCCFactory)

res = bs.sample(problem, np.linspace(0.5, 3.0, 20))
print(res)
```

### What is the expected behavior?

The `BOPESSampler` should support `MininmumEigensolverFactory` classes.

### Suggested solutions

Add a check similar to the one in the `GroundStateEigensolver`: https://github.com/Qiskit/qiskit-nature/blob/main/qiskit_nature/algorithms/ground_state_solvers/ground_state_eigensolver.py#L103-L105

**Comment by iuliazidaru** [comment]
May I try to solve this issue?

**Comment by mrossinek** [comment]
> May I try to solve this issue?

Sure, please go ahead! :slightly_smiling_face::+1:

**Comment by iuliazidaru** [comment]
I need a bit of help.

In sample I see that we have to use **ElectronicStructureMoleculeDriver**:
`raise QiskitNatureError(
                "Driver must be ElectronicStructureMoleculeDriver or VibrationalStructureMoleculeDriver."
            )
`

I am trying to obtain a solver:
 ```
 solver= VQEUCCFactory(quantum_instance).get_solver(problem, converter)
  File "/.../qiskit-nature/qiskit_nature/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_ucc_factory.py", line 203, in get_solver
    particle_number = cast(ParticleNumber, driver_result.get_property(ParticleNumber))
AttributeError: 'NoneType' object has no attribute 'get_property'
```
The NoneType is `problem.grouped_property_transformed`. It is populated when **second-quantized** operators are generated. (`problem.second_q_ops()`). I didn't see this call on a problem built with ElectronicStructureMoleculeDriver and I get an error when making the call:
`  File "/.../qiskit-nature/qiskit_nature/drivers/second_quantization/pyscfd/pyscfdriver.py", line 510, in run_pyscf
    method_cls = getattr(scf, method_name)
AttributeError: module 'pyscf.scf' has no attribute 'PYSCFDRIVER'`
What am I missing about this driver?

Thank you!

**Comment by mrossinek** [comment]
I've had an offline discussion with @woodsp-ibm regarding PR #457. The question arose whether we really want to support a syntax like the one proposed there: `gss: Union[GroundStateSolver, MinimumEigensolverFactory]` + require a `QubitConverter` in the latter case...
Or whether instead we should stick to the (arguably more obvious) solution of doing:
```
BopesSampler(
    GroundStateEigensolver(
        some_qubit_converter,
        VQEUCCFactory(some_quantum_instance),
    )
)
```
I.e. instead of adding support for the factory directly inside of the `BopesSampler`, we should instead make sure that it knows how to handle a GSS which was initialized with a factory.

Unfortunately the code snippet in my original description of this issue at the top here is not valid (I don't quite know how that happened), but this latter case is still flawed as it does not work as intended today either. Here is a new snippet:
```python
from functools import partial

import numpy as np

from qiskit.providers.aer import StatevectorSimulator
from qiskit_nature.algorithms.ground_state_solvers import GroundStateEigensolver
from qiskit_nature.algorithms.ground_state_solvers.minimum_eigensolver_factories import (
    VQEUCCFactory,
)
from qiskit_nature.algorithms.pes_samplers import BOPESSampler
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.drivers import Molecule
from qiskit_nature.drivers.second_quantization import (
    ElectronicStructureDriverType,
    ElectronicStructureMoleculeDriver,
)
from qiskit_nature.mappers.second_quantization import ParityMapper
from qiskit_nature.problems.second_quantization.electronic import ElectronicStructureProblem

stretch = partial(Molecule.absolute_distance, atom_pair=(0, 1))

molecule = Molecule(
    geometry=[
        ["H", [0.0, 0.0, 0.0]],
        ["H", [0.0, 0.0, 1.0]],
    ],
    degrees_of_freedom=[stretch],
)
driver = ElectronicStructureMoleculeDriver(molecule, "sto3g", driver_type=ElectronicStructureDriverType.PYSCF)
problem = ElectronicStructureProblem(driver)

converter = QubitConverter(ParityMapper())

solver = GroundStateEigensolver(converter, VQEUCCFactory(StatevectorSimulator()))

bs = BOPESSampler(solver)

res = bs.sample(problem, np.linspace(0.5, 3.0, 2))
print(res.point_results)
```
It produces the following error when using the latest `main` installations of Qiskit Nature and Terra:
```
Traceback (most recent call last):
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/tmp2.py", line 38, in <m
    res = bs.sample(problem, np.linspace(0.5, 3.0, 2))
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/qiskit_nature/algorithms
    self._raw_results = self._run_points(points)
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/qiskit_nature/algorithms
    raw_result = self._run_single_point(point)  # dict of results
  File "/home/oss/Files/Qiskit/src/qiskit-nature/main/qiskit_nature/algorithms
    self._points_optparams[point] = optimal_params
TypeError: 'NoneType' object does not support item assignment
```
I believe if we try to fix that error instead, we do not need the proposal of #457 as it is potentially too convoluted.

@iuliazidaru I am sorry that you have already put so much work into that PR. Would you still be interested in attempting this new approach, instead? :slightly_smiling_face:

**Comment by iuliazidaru** [comment]
@mrossinek Yes, I'll check this next week.
