### ISSUE TITLE
Design Overview (discussion)

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#4]
Migrated from Enterprise Github.
Creator: @mrossinek

Let's use this issue for general discussions which do not fit into a specific issue (yet).
To get this started, here is the updated overview of `qiskit_nature`.

EDIT: I uncommented the oudated UML diagram. Please see the last comment of this issue for the most up-to-date version.

**Comment by manoelmarques** [comment]
Creator: @mrossinek

And here is the updated overview UML:
![Qiskit_Nature](https://media.github.ibm.com/user/251930/files/3d50d000-5b36-11eb-8da1-d910061b9588)

As you can see, through the removal of `SecondQuantizedSumOp` we can now define all other interfaces dependent on `SumOp`. This allows the use of any `SumOp` implementation as a standalone object and the case of `SecondQuantizedOperator` (when required) can be used by the user with the `.map()` and `.transform()` methods which could look similar to this:
```python
def map(self, fermionic_mapper=None, bosonic_mapper=None, spin_mapper=None):
    fermionic_pauli_sum_op = fermionic_mapper.map(self.fermionic)
    bosonic_pauli_sum_op = bosonic_mapper.map(self.bosonic)
    for spin, spin_sum_op in self.spin.items():
         spin_pauli_sum_ops[spin] = spin_mapper.map(spin_sum_op)
    # do whatever post-processing we need to do here...

def transform(self, fermionic_transformer=None, ...):
    # similar to above
```

Obviously, we can also specify other defaults than `None` in any of these cases.

**Comment by mrossinek** [comment]
For completeness; here is the most up-to-date version of the UML. It is becoming a little bit crowded so I will update individual issues with close-up figures of the respective parts.
![Qiskit_Nature](https://user-images.githubusercontent.com/21973473/106932741-610c3c80-6718-11eb-9132-8482c8b1503c.png)

**Comment by mrossinek** [comment]
Once again, here is the updated UML diagram of the design overview:
![Qiskit_Nature](https://user-images.githubusercontent.com/21973473/107226739-c7e06d00-6a1a-11eb-9208-ff49d81eed6f.png)

**Comment by mrossinek** [comment]
Another update:
![Qiskit_Nature](https://user-images.githubusercontent.com/21973473/107746191-b3032280-6d15-11eb-9273-8817d9bbb30c.png)

Most notable changes:
- removal of `SpinOp`
- instead, problems which would have made use of this can construct a `BosonicOp` which is the most abstract representation
- examples are commented in e.g. the `LatticeModel` and `VibronicStructureProblem`

**Comment by mrossinek** [comment]
Since the overall design is no longer an open discussion and the last update of this thread is out-of-date again I am closing this issue now.
