### ISSUE TITLE
Re-organize unit tests along folder structure as per code

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#40]
Re-organize unit tests such that instead of a flat structure they are in a folder structure akin to the code.

We may want to adopt the same structure as Terra under test where they have different folders with the units tests under a `python` folder.

**Comment by mrossinek** [comment]
I am not sure whether the `python` subfolder really makes sense in our case. To my understanding that is done in Terra in order to keep the tests for the `ipynb` integration tools separate, right?

**Comment by manoelmarques** [comment]
Yes, unless there is any thought of having jupyter tests in the future, it seems redundant. Terra also has this test/randomized folder which it is all python tests, so I don't know why they didn't include it under their python folder.

**Comment by woodsp-ibm** [comment]
Since it seemed to make things consistent it seemed to do no harm even if we never added any other types. Of course if other types were added then it would be simple enough to move the tests into such a folder if it weren't done now. I don't have a strong opinion one way or the other.

**Comment by mrossinek** [comment]
I am also not opinionated on this. Just wanted to make the observation.
@manoelmarques Since you are assigned here, feel free to go ahead with either option :+1:
