### ISSUE TITLE
ModuleNotFoundError: No module named 'qiskit_nature.drivers.second_quantization'

### ISSUE THREAD

**Issue by gonzrubio** [Qiskit/qiskit-nature#410]
### Information

- **Qiskit Nature version**: 0.1.4
- **Python version**: 3.9.5
- **Operating system**: Windows10

### What is the current behavior?
ModuleNotFoundError: No module named 'qiskit_nature.drivers.second_quantization'

### Steps to reproduce the problem
from qiskit_nature.drivers import Molecule
from qiskit_nature.drivers.second_quantization import ElectronicStructureDriverType
from qiskit_nature.drivers.second_quantization import ElectronicStructureMoleculeDriver

### What is the expected behavior?
%whos

Variable                                                   Type                                     Data/Info
ElectronicStructureDriverType           EnumMeta                             <enum 'ElectronicStructureDriverType'>
ElectronicStructureMoleculeDriver     ABCMeta                              <class 'qiskit_nature.dri<...>StructureMoleculeDriver'>
Molecule                                                 type                                  <class 'qiskit_nature.drivers.molecule.Molecule'>

**Comment by woodsp-ibm** [comment]
The cause of the issue you report is this

> Qiskit Nature version: 0.1.4

The drivers were refactored in version 2 so you need to update your Nature install to run any code that imports the drivers from their new refactored location - the latest version is 0.2.2.
