### ISSUE TITLE
QEOM evaluation of operators

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#415]
In unit test module [algorithms/excited_state_solvers/test_bosonic_esc_calculation.py](https://github.com/Qiskit/qiskit-nature/blob/main/test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py) the test [test_vqe_uvccsd_factory()](https://github.com/Qiskit/qiskit-nature/blob/f73b8c182451939f3f386389291156a813cdfa53/test/algorithms/excited_state_solvers/test_bosonic_esc_calculation.py#L112-L123) uses the `aer_simulator_statevector` (a statevector simulator).

Now switching to `aer_simulator` and adding `include_custom=True` to the `VQEUVCCFactory` constructor, I think should also be an ideal result with the same outcome as the statevector. Internally `VQE` will use `AerPauliExpectation` which will use the custom Aer instruction in the expectation computation and produces an ideal result. The aforementioned test however **_fails_** under this configuration as the result ends up outside the limits allowed by the test.

In looking at QEOM, which in turn uses an `evaluate_operators` in the GroundStateSolver, I have some observations. First VQE, when using include_custom=True, returns a dictionary computed from counts
```
    'eigenstate': {'0101': 0.9960860906568267, '1001': 0.08838834764831845},
```
versus what I might have expected it to look like as comes from the statevector result
```
    'eigenstate': array([-4.90652305e-17+1.59462423e-17j,  2.15105711e-16-4.65078744e-16j,
        1.23327997e-18+2.94357950e-17j, -1.11022302e-16-4.68375339e-17j,
        1.23881957e-16-2.25705481e-16j,  9.95269314e-01+1.40225427e-16j,
        7.31772069e-05+1.06710345e-16j,  3.29597460e-17+4.93038066e-32j,
       -7.46392098e-17+5.76507565e-17j,  9.71544362e-02-5.94899346e-18j,
        6.12208684e-05-6.86833149e-17j,  1.16971296e-16-7.11236625e-17j,
        9.19962484e-17+2.94377830e-17j, -3.33066907e-16+3.64099743e-17j,
        4.90533720e-17+6.01023954e-17j, -1.21430643e-17+1.66533454e-16j]),
```
as an ideal result. Since the former is computed from counts it will not be ideal. Maybe this is fine, its not what I expected, I would have thought VQE would have given an ideal state back, like it does for statevector, buts it's logic to compute the eigenstate does not do that. The state is used in Nature in its evaluation of the matrix operators.

Either way it seems that perhaps the computation could be improved. But rather than try to fix this now - since its working albeit it could be improved, perhaps this is something that needs more change/improvements here in Nature as well as in Terra.

Maybe we should have some call on the minimum eigensolvers that given a result from an instance, if you pass that into some method say compute_expectation(operator, MinimumEigenSolverResult) it will compute an expectation (if it can do so - i.e. supports aux operator) where it can take whatever it needs from the result to compute the expectation at that same result state. Maybe we allow it to be a union for VQE to allow any parameters to be passed - then in the future it will just use the planned expectation object directly at that parameterization. This would allow the logic to go closer to the algorithms in Terra and away from the ground state solvers in Nature.

So I figured I'd raise this issue for potential discussion/consideration going forwards on improving Nature and the algorithms in Terra based on needs like this.

**Comment by mrossinek** [comment]
I am not sure I grasp all the details of this just yet but it seems rather familiar...
Could this possibly be related to #52?

**Comment by woodsp-ibm** [comment]
With the primitive based algorithms being the future, that includes a new VQE based on Estimator, where there is no direct state as such in the result, this is no longer relevant.
