### ISSUE TITLE
Error installing PySCF library

### ISSUE THREAD

**Issue by pranavm1502** [Qiskit/qiskit-nature#416]
### Information

- **Qiskit Nature version**: 0.2.2
- **Python version**: 3.8.8
- **Operating system**: Mac OS Big Sur 11.2.3

### What is the current behavior?
```
error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyscf
```

### Steps to reproduce the problem
pip install ' qiskit-nature[pyscf]'

### What is the expected behavior?
Successful installation

### Suggested solutions
There seems to have been a similar issue with the direct installation of PySCF package, refer -
https://github.com/pyscf/pyscf/issues/1095

**Comment by JoelHBierman** [comment]
There are a few known issues for installing pyscf on macOS, but it seems possible to do. See pyscf#1096.

**Comment by woodsp-ibm** [comment]
If you install pyscf via qiskit nature extra requires i.e. `pip install qiskit-nature[pyscf]` then it will install compatible versions that we test with and are known to work (at present it limits things to 1.7.6). There is a PR here #414 that is addressing the new version of PySCF that was recently released.

**Comment by pranavm1502** [comment]
Thanks! `pip install qiskit-nature[pyscf] -U` worked now.

**Comment by Balasathish301** [comment]
Hi,we are doing quantum project using qiskit. but we are struggling to install the libraries and packages. Please say how to install or import the libraries. please help us. if anybody knows tell some ideas to us.

**Comment by woodsp-ibm** [comment]
This covers installation https://qiskit-community.github.io/qiskit-nature/getting_started.html - anything beyond that you would need to be more specific. If it Windows you have and are trying to install PySCF there are no binaries built for that - PySCF has install instructions of its own https://pyscf.org/install.html
