### ISSUE TITLE
Question about the protein folding tutorial

### ISSUE THREAD

**Issue by tony9664** [Qiskit/qiskit-nature#424]
### What is the expected enhancement?

I read the protein folding tutorial (https://github.com/Qiskit/qiskit-nature/blob/main/docs/tutorials/09_Protein_Folding.ipynb) and get confused about the 'side chain' term used in the document. Naturally a protein is folded from a single linear chain of amino acids, without any branches. The term 'side chain' is used to refer to the functional groups (or R groups) of the amino acids ( a methyl group for example). However the tutorial seems to imply that one or more whole amino acids can be attached as side chains. Although this could be done under the course grained model, it might not be physically meaningful.

**Comment by pbark** [comment]
Hi @tony9664 , 

thanks a lot for checking out the tutorial on protein folding. Currently for side chains in the problem we support one single bead (aminoacid) per side chain binding point. The definition of side chains in organic chemistry (as a functional group) is not the same as the one for aminoacid side chains used more in biochemistry. Here we follow the later and in a general case amino acid side chains are playing a critical role in interactions that eventually lead to protein folding. I am sorry for the confusion and I hope this clarifies your point.

**Comment by tony9664** [comment]
Thanks for answering. If I am understanding correctly, the course-grained model from Miyazawa et al used one bead to represent a whole residue and all the atomic details are lost ( including backbone atoms C,O,N,H and sidechain atoms). Therefore, using one bead for each residue should be good enough (like Figure 2(b) of this paper https://www.nature.com/articles/s41534-021-00368-4 ). Adding one or more additional beads as "side chains" may not help or could even make it worse, since the interactions were not designed to represent a amino acid by more than one bead.
