### ISSUE TITLE
Allow broader use of VQEClient in Nature

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#426]
While VQEClient is a MimimumEigenSolver and can be used in those contexts there are other places where we should be able to allow this to be used/leveraged but have not so far.

1. In mininum eigen solver factories that are building for example VQE+UCCSD that could be built out with VQEClient see #384 in which I commented in this regard.

2. For BopesSampler. With the extrapolation its looking for a VariationalAlgorithm interface that VQE implements but VQEClient does not. We should consider having it implement that interface to allow its use with BopesSampler.

**Comment by mrossinek** [comment]
Thanks, @woodsp-ibm! This is very good point. In fact, I think your second point:
> For BopesSampler. With the extrapolation its looking for a VariationalAlgorithm interface that VQE implements by VQEClient does not. We should consider having it implement that interface to allow its use with BopesSampler.

could also be solved by fixing #398. However, I agree that having the `VQEClient` implement the `VariationalAlgorithm` interface is also a good idea. Maybe we should do all three of these improvements :+1:

**Comment by woodsp-ibm** [comment]
Lets do a separate PR. And as to timing, I think better next release.

**Comment by mrossinek** [comment]
With the move to the primitive-based algorithms released as part of Qiskit Terra 0.22 (which will be supported starting with Qiskit Nature 0.5) the usage of the `VQEClient` is discouraged.

See also #849 and #856
