### ISSUE TITLE
Source Code for DFT Quantum Code Not Available

### ISSUE THREAD

**Issue by HenryMakowitz** [Qiskit/qiskit-nature#429]
### What is the expected enhancement? Source Code Availability 

Sirs ;

You state in your Article cited below that your source code will be available.
When will it be placed in the cited repository ? I checked today and I did not
( or could not ) find it. Please advice.

Re: Your Article ; " Quantum HF/DFT-embedding algorithms for electronic
structure calculations: Scaling up to complex molecular systems ".
J. Chem. Phys. 154, 114105 (2021)

Your Article states ;
" The source code will be made available in the Github repository per ( Ref 59 ) "

( Ref 59 ) See https://github.com/Qiskit/qiskit-nature/ for Qiskit, Qiskit Nature; accessed
29 January 2021.

Best,
Dr. Henry Makowitz, PhD
CEO and Founder
Imagineering Technologies, Inc.
PO Box 2913
Idaho Falls, Idaho 83403-2913 USA
Tel ( 208 ) 524-2719

**Comment by mrossinek** [comment]
The DFT Embedding is actively being worked upon and we will publish it once the implementation is of production quality and integrated properly into Qiskit Nature.
We are tracking the progress over in #26, which you can subscribe to (in the right-hand column) in order to receive updates.
