### ISSUE TITLE
Runtime programs should store the history w/o requiring active user-server link

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-nature#444]
### What should we add?

To obtain the history of a VQE run right now, we pass a callback into the `VQEClient` that forwards information from the energy evaluation on the runtime server back to the user. However, if the connection between the user and server is interrupted, the information is lost until the connection is manually restored. 

It would be great if instead we could also store the callback information on the server and return it inside the result object.

**Comment by woodsp-ibm** [comment]
In caching it on the server, how about just repeatedly calling the callback with any cached values when the connection is restored. Hence a user would see 'normal' behavior and not have to deal with say plotting the rest of the graph where part of what normally came via the callback came in the result. Yes the timing would look different with a bunch of calls being given in a burst, but I think that can easily be noted in any docs regarding the behavior.

**Comment by Cryoris** [comment]
That would be another option, but detecting that the stream broke and automatically reconnecting is probably more difficult to implement. Also, we could think of just allowing a flag to store the data without having to pass a callback function which would be even simpler for the users.

**Comment by woodsp-ibm** [comment]
Having the data all at once at the end seems fine - more of a post-mortem approach. The callback allows one to monitor as things are progressing, so in my mind it would be nice if things could continue after an interruption. Of course if the algorithm has run to the end its more or less the same except being in the result you have to code to handle/process it that way too from the result; maybe we could even have a utility if this seems desirable that uses the users callback along with the result.

**Comment by mrossinek** [comment]
Closing this as per https://github.com/Qiskit/qiskit-nature/pull/1124
