### ISSUE TITLE
Data structures for quadratic and other Hamiltonians

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#460]
### What should we add?

A quadratic Hamiltonian is composed of terms that are quadratic in the ladder operators:
![image](https://user-images.githubusercontent.com/4296166/145867381-4f14e16d-e312-4446-82ad-0eb1a860452d.png)
Quadratic Hamiltonians arise in mean-field models and their eigenstates are an important class of states that can be efficiently prepared on a quantum computer. The most convenient way to represent quadratic Hamiltonians is by storing the coefficients `M_pq` and `Δ_pq` as matrices because they need to be processed with linear algebra routines in order to get the eigenstates of the Hamiltonian. Therefore, the `FermionicOp` class is not a convenient way to represent them. This observation applies more generally; for example, the most convenient way to represent a molecular Hamiltonian is often to store the one-body and two-body tensors as numpy arrays. In OpenFermion, these numpy array representations are encompassed by the PolynomialTensor class, and the implementation in Qiskit Nature could use that as a model.

As a first step, I would like to add a `QuadraticHamiltonian` class that stores the matrices `M_pq` and `Δ_pq`. This class probably belongs in `qiskit_nature.operators`, but it's not clear whether it belongs in `qiskit_nature.operators.second_quantization` because it will not inherit from `SecondQuantizedOp`.

**Comment by kevinsung** [comment]
During offline discussion with @mrossinek, we considered adding a class analogous to PolynomialTensor from OpenFermion that both QuadraticHamiltonian and the electronic integral classes would inherit from. Upon further investigation, I have found that while this is possible, some tradeoffs would need to be made.

PolynomialTensor stores the coefficients of creation and annihilation operators in a dictionary of tensors. Let's call the dictionary `tensors`. Then `tensors[(1, 0)]` would be an `N x N` matrix storing the coefficients of `+_i -_j` and `tensors[(1, 1, 0, 0)]` would be an `N x N x N x N` tensor storing the coefficients of `+_i +_j -_k -_l`. These are enough to represent the one- and two- body integrals. For QuadraticHamiltonian, we would also have `tensors[(1, 1)]` which stores the coefficients of `+_i +_j`. Note that the concept of "spin" is absent here, which is consistent with FermionicOp, and reasonable because these are supposed to be representations of general operators.

The `OneBodyElectronicIntegrals` and `TwoBodyElectronicIntegrals` explicitly account for spin. For example, `TwoBodyElectronicIntegrals` stores the integrals in two possible formats. One of the possible formats is as four separate tensors, where each tensor stores the interactions between a combination of alpha and beta spin orbitals. The total storage space in this situation is `4 * N^4` where N is the number of _spatial_ orbitals. If we were to add PolynomialTensor and make `TwoBodyElectronicIntegrals` inherit from it, then we would have to assemble those tensors into a larger tensor of size `(2 * N)^4 = 16 * N^4` because PolynomialTensor does not keep track of spin. This is 4 times as much space as before.

If `TwoBodyElectronicIntegrals` was designed specifically to save space by storing the integrals for different spin interactions separately, then inheriting from PolynomialTensor would eliminate that benefit. In this case, the electronic integrals classes should _not_ inherit from PolynomialTensor. And if this is the case, then I don't see a compelling reason to add PolynomialTensor.

@mrossinek thoughts?

**Comment by mrossinek** [comment]
I did not have in mind to follow the implementation of `PolynomialTensor` to such a close degree. To my understanding the discussion evolved more around finding a common matrix-based container base class which can be used by both, the `ElectronicIntegrals` and the `QuadraticHamiltonian`.

I will need to think about this in more detail next week. A quick pointer however that #533 reduces the memory requirements of the `TwoBodyElectronicIntegrals` for the scenario of a restricted spin calculation by a factor of 4. The general underlying structure is not changed but it is kept as sparse as during initialization.

**Comment by kevinsung** [comment]
I see. The way that `ElectronicIntegrals` explicitly accounts for spin and uses that information for space savings seems somewhat at odds with a class like `QuadraticHamiltonian` that is meant to represent general operators, so my current recommendation is that we should keep them separate.

**Comment by mrossinek** [comment]
I am closing this issue with the following notes:
- an initial `QuadraticHamiltonian` class has been added via #482 and will be part of the upcoming 0.4 release
- a new design has been proposed in #665, which supersedes this discussion
