### ISSUE TITLE
spell check fails locally

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#463]
### Environment

- **Qiskit Nature version**: dcdd1ddc6da85cbecaeae9b3689af1548fd1e8aa
- **Python version**: 3.6, 3.9
- **Operating system**: RHEL 8.5

### What is happening?

The spell check fails locally. This is giving me problems with debugging the CI failure at #462 .

### How can we reproduce the issue?

1. Create a fresh virtual environment
2. Install qiskit-nature from source, along with the dev tools.
3. Run `make spell`.

Result:
Many errors are thrown. Excerpt:
```
% make spell                       
python -m pylint -rn --disable=all --enable=spelling --spelling-dict=en_US --spelling-private-dict-file=.pylintdict --ignore=gauopen qiskit_nature test tools
************* Module qiskit_nature.algorithms.excited_states_solvers.excited_states_eigensolver
qiskit_nature/algorithms/excited_states_solvers/excited_states_eigensolver.py:40:0: C0402: Wrong spelling of a word 'commutativity' in a docstring:
                             commutativity information returned by this method.
                             ^^^^^^^^^^^^^
Did you mean: ''commutative' or 'commutation' or 'commutativities''? (wrong-spelling-in-docstring)
************* Module qiskit_nature.circuit.library.ansatzes.chc
qiskit_nature/circuit/library/ansatzes/chc.py:42:0: C0402: Wrong spelling of a word 'tuples' in a docstring:
            excitations: The list of excitations encoded as tuples of tuples. Each tuple in the list
                                                            ^^^^^^
Did you mean: ''letups' or 'pes' or 'bopes' or 'utils''? (wrong-spelling-in-docstring)
qiskit_nature/circuit/library/ansatzes/chc.py:42:0: C0402: Wrong spelling of a word 'tuples' in a docstring:
            excitations: The list of excitations encoded as tuples of tuples. Each tuple in the list
                                                                      ^^^^^^
Did you mean: ''letups' or 'pes' or 'bopes' or 'utils''? (wrong-spelling-in-docstring)
qiskit_nature/circuit/library/ansatzes/chc.py:42:0: C0402: Wrong spelling of a word 'tuple' in a docstring:
            excitations: The list of excitations encoded as tuples of tuples. Each tuple in the list
                                                                                   ^^^^^
...
```

### What should happen?

No errors are displayed.

**Comment by mrossinek** [comment]
I ran into the same problem in the past. Somehow the standard english dictionary installed in the OS used by the CIs (I think that's Ubuntu-based) does not match the dictionary installed in Fedora/RHEL. I have worked around this by extending the local dictionary of my OS with the list of words which fail on `main`. I'm on a different machine right now so cannot check which path this is really in. I can update here tomorrow in case you do not figure it out based on this comment already :+1:

**Comment by mrossinek** [comment]
Alright you should be able to add the missing words to `~/.config/enchant/en_US.dic`. Here are the contents of mine:
```
amino
commutativity
filename
gcc
hermitian
meth
multi
parameterized
peptide
quantization
radians
refactored
reinstall
tb
timestamp
tuple
tuples
uhf
username
versa
```
Let me know if this fixes things for you :+1:

**Comment by kevinsung** [comment]
Thanks @mrossinek , that fixed those errors. If this is the best solution, then it should at least be documented somewhere, so I suggest we leave this issue open until that is done or a better solution is found.
