### ISSUE TITLE
Type check edge weights in ``Lattice`` constructions?

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-nature#466]
### What is the expected enhancement?

Right now, a ``Lattice`` can be constructed from a graph with any value for the edge weights, e.g.
```python
>>> from qiskit_nature.problems.second_quantization.lattice import Lattice
>>> import retworkx as rx
>>> graph = rx.PyGraph(multigraph=False)
>>> graph.add_nodes_from(range(2))
>>> graph.add_edges_from([(0, 1, "dilution fridge")])
>>> Lattice(graph)
```
In the above case, the construction of a second quantized op or a qubit op based on the lattice will obviously fail. But there might be more subtle cases.

It would be nice to type check the weights and ensure that they are numeric (or in some supported format). Or is there a reason to support arbitrary types as weights?

**Comment by mrossinek** [comment]
Closed by #471 (aa910c9e8fda690535c9a1634b91c10cf0c682db)
