### ISSUE TITLE
FermionicOp initializes successfully but throws IndexError on method call

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#473]
### Environment

- **Qiskit Nature version**: e39594b8ede4533af7d22b2b121f29d624e569ed
- **Python version**: 3.9
- **Operating system**: RHEL 8.5

### What is happening?

FermionicOp initializes successfully but throws IndexError on method call.

### How can we reproduce the issue?

Code:
```python
op = FermionicOp([("+_1", 1.0), ("", 1.0)])
print(op)
```
Result:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-58-3a1c34389858> in <module>
      1 op = FermionicOp([("+_1", 1.0), ("", 1.0)])
----> 2 print(op)

~/projects/qiskit-nature/qiskit_nature/operators/second_quantization/fermionic_op.py in __str__(self)
    370         )
    371         ret = "  " + "\n+ ".join(
--> 372             [f"{coeff} * ( {label} )" if label else f"{coeff}" for label, coeff in self.to_list()]
    373         )
    374         if FermionicOp._truncate and len(ret) > FermionicOp._truncate:

~/projects/qiskit-nature/qiskit_nature/operators/second_quantization/fermionic_op.py in to_list(self, display_format)
    464                 for label_data, coeff in self._data
    465             ]
--> 466         return self._to_dense_label_data()
    467 
    468     def to_matrix(self, sparse: Optional[bool] = True) -> Union[csc_matrix, np.ndarray]:

~/projects/qiskit-nature/qiskit_nature/operators/second_quantization/fermionic_op.py in _to_dense_label_data(self)
    589                 char = "+" if fer_label.is_creation else "-"
    590                 index = fer_label.index
--> 591                 if (label_list[index], char) in _ZERO_LABELS:
    592                     break
    593                 label_list[index] = _MAPPING[(label_list[index], char)]

IndexError: list index out of range
```

### What should happen?

No error should occur.

### Any suggestions?

It seems to have something to do with the identity term (empty string label). If the register length is specified, then it works fine, e.g.
```python
op = FermionicOp([("+_1", 1.0), ("", 1.0)], register_length=2)
print(op)
```

**Comment by mrossinek** [comment]
I'm actually surprised that the initialization of `FermionicOp([("+_1", 1.0), ("", 1.0)])` is working. It should _not_.
When using sparse labels, you have to specify `register_length`, otherwise the operator cannot know it's size. Thus, your suggestion at the end is actually the only way that this should work.

I'm leaving this open as a bug until we raise the correct error upon initialization.

**Comment by kevinsung** [comment]
I don't think you should be forced to specify a register length when initializing a FermionicOp using sparse labels. A creation operator acting on a particular fermionic mode is a valid operator regardless of how many total modes there are.

**Comment by ikkoham** [comment]
The `register_length` is supposed to be inferred automatically (the largest index + 1), so I assume it is not working.
In any case (regardless of whether it is inferred or given,), register_length is required.
