### ISSUE TITLE
Support `UnitsType.BOHR` in `Molecule`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#477]
### What is the expected enhancement?

Currently the `Molecule` class requires coordinates in Angstrom and is not capable of handling other unit types by itself.
In fact, it does not even take a `units` argument to its constructor based on which one could guard against unit-related errors such as the one fixed by #476.

Thus, the following things can be improved:
- add a `unit` (or `units` ?) argument to `Molecule.__init__`
- interpret said argument and always store in Angstrom internally (to make things consistent)
- take the original `unit` argument into account in `Molecule.__str__` and print the coordinates in the format used during construction to avoid confusion of the user

**Comment by Ryand1234** [comment]
Can I work on this issue?

**Comment by mrossinek** [comment]
Sure, please go ahead! :)
