### ISSUE TITLE
Runtime VQEProgram error

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-nature#480]
### Environment

- **Qiskit Nature version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

Related to: https://github.com/Qiskit/qiskit-ibm-runtime/issues/63

The problem is that the number of outputs returned does not match the inputs, even though 6 auxiliary operators are input. This is a problem on the Runtime server side, but I'll leave it as an issue to keep track.

### How can we reproduce the issue?

Just run the tutorial `tutorials/07_leveraging_qiskit_runtime.html`.

### What should happen?

work

**Comment by mrossinek** [comment]
This was actually solved in Qiskit Nature 0.3.0. The reason it went unnoticed is that the issue in qiskit-ibm-runtime got opened the day that 0.3.0 was released. That issue was closed yesterday, so I am closing this one too.
