### ISSUE TITLE
What is the default reference state for the UCCSD ansatz?

### ISSUE THREAD

**Issue by JoelHBierman** [Qiskit/qiskit-nature#489]
Hi, this issue is mainly a question that pertains to the documentation for the UCC and UCCSD ansatzes. The unitary coupled cluster ansatz is typically defined with respect to some specified reference state. This could be the Hartree Fock state, but it does not necessarily have to be. For UCCSD, the T_1 and T_2 operators consist of a summation over an index of orbitals that are unoccupied in the reference state and an index of orbitals which are occupied in the reference state. What's not clear to me from the documentation on `UCC` and `UCCSD` is how Qiskit determines which orbitals are occupied and which are unoccupied when creating an instance of either of these two class objects, given that it's not necessary for you to explicitly provide it a reference state. 

There are other constraints that you must provide, such as restricting the Ansatz to single/single-double excitations, the number of electrons, the number of spin electrons, ect... but these by themselves do not seem to be enough to uniquely specify a reference state or which spin orbitals are unoccupied/occupied. Does Qiskit default to the generalized version of UCCSD (where all excitation operators subject to the other constraints are included) or does it implicitly default to some other reference state? The former seems strange since it would effectively override the default `generalized=False` argument. Defaulting to some reference state unspecified in the documentation (probably something reasonable such as the Hartree Fock state) seems opaque and less than ideal since it assumes that the user has this particular reference state in mind. Given that running the line of code:

`print(generate_fermionic_excitations(num_spin_orbitals=6, num_particles=(1,1), num_excitations=1))`

returns:

`[((0,), (1,)), ((0,), (2,)), ((3,), (4,)), ((3,), (5,))]`

it seems that the likely default reference state for `UCCSD` is the Hartree Fock state, but any insight or information on what is going on under the hood would be greatly appreciated.

**Comment by mrossinek** [comment]
Hi @JoelHBierman :slightly_smiling_face: 

You are raising a very good question! I just double checked the [docs](https://qiskit.org/documentation/nature/stubs/qiskit_nature.circuit.library.UCC.html#qiskit_nature.circuit.library.UCC) and you are absolutely right, that they are quite ambiguous.

The `UCC` Ansatz was historically developed in conjunction with ground-state calculations. As such, it has the Hartree-Fock ground state baked into it. As you have correctly pointed out, the `generalized=True` keyword argument can be used to change that behavior.

Does this answer your question?

We should update the documentation to unambiguously reflect this. Thus, I will leave this issue open until that is done.

**Comment by JoelHBierman** [comment]
Thank you for clarifying on this! One more question:

Is the `initial_state` argument independent of how Qiskit determines what the "reference state" is? I am pretty sure the answer to this is "yes", but I would just like to make sure. 

So for instance, if a user passes `None` to the `initial_state`, will it default to prepending a `HartreeFock` circuit to the beginning to the Ansatz circuit, then use this `initial_state` as the effective "reference state" from which the excitation operators are generated? Similarly, if one specifies `initial_state=my_initial_state`, would it use `my_initial_state` as an effective reference state to generate the excitation operators? I think the answer to both of these is "no" because 1. `initial_state` is an argument passed to other circuit object types that do not involve excitation operators, so it makes sense for the functionality of this argument to be the same across all instances where it is used. 2. The moment a user passes an `initial_state` that is a superposition of different Slater determinant states, the occupation number of `initial_state` ceases to be well-defined.

Conceptually, it's slightly confusing because `initial_state` sounds like it _could_ play the role of a reference state, but it does not appear as if it is treated this way (nor do I think you would want it to- it's easy to think of instances where you might run into trouble if it was) in Qiskit.

**Comment by mrossinek** [comment]
The excitations generated by the `UCC` ansatz (and its base classes) are **independent** of what you choose for `initial_state`. It is the user's responsibility to match these (which is not difficult because as of now we only have the `HartreeFock` initial state).

You're right that this is slightly confusing and we will clarify this in the documentation. The reason that you can pass an `initial_state` to the `UCC` base class in the first place is because of how the Ansatz get's propagated down to the `VQE` (as one quantum circuit).
