### ISSUE TITLE
Initialize FermionicOp with tuple as label

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#493]
### What is the expected enhancement?

The only way to initialize a FermionicOp is by providing a string label (i.e. `"II+"` or `"+_2"`, etc.). This is awkward when writing code that generates FermionicOps programmatically, where it is much more natural to use a tuple `(index, action)` instead, (i.e. `(2, 1)` instead of `"+_2"`).

**Comment by ikkoham** [comment]
Thank you. Similar to my comment: https://github.com/Qiskit/qiskit-terra/pull/7401#issuecomment-994813989

@mrossinek @kevinsung Open question. which is better `(index, action)` or `(action, index)`?
Which type of action do you prefer? (integer: creation 1, annihilation 0, boolean: True for creation, False for annihilation, string: "+" and "-")

**Comment by kevinsung** [comment]
On further thought I prefer `(action, index)` because the string labels `X_i` and `+_i` have the same order.

I think the actions should be integers because it may be useful to perform arithmetic on them. I prefer 1 for creation and 0 for annihilation.

This may be beyond the scope of this issue but I think it would be useful to generalize the "action" concept. For example, we could allow it to be a Pauli object. By letting the action be an object and implementing arithmetic for its class, we would get arithmetic for the sum objects for free.

We could also generalize the "index" concept. It could be a qubit or fermionic mode object instead of just an index. That way we could attach properties to the qubits that carry information such as adjacency, and that information would automatically be transferred to the sum object.

**Comment by mrossinek** [comment]
> On further thought I prefer (action, index) because the string labels X_i and +_i have the same order.
> I think the actions should be integers because it may be useful to perform arithmetic on them. I prefer 1 for creation and 0 for annihilation.

I agree with this :+1: 

The generalizations of the action and index require some more discussion in my opinion. In that sense I think that these are indeed outside the scope of this issue.
