### ISSUE TITLE
Replace QMolecule with DriverResult

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#5]
Migrated from Enterprise Github.
Creator: @mrossinek

### What is the expected enhancement?

In the old Qiskit Aqua, all runtime specific information generated by a driver were stored in the `QMolecule` class, which will not be moved to Qiskit Nature.
However, we are still in need of a container for all of this information and it should not only be stored centrally by the `problems`-wrappers because these wrappers should really only compose the functionality of other pluggables. In this way, the user also has the flexibility and power to use this information outside of a `problems`-wrapper.

Thus:

- We need to adapt the drivers to produce a `DriverResult` which should store all runtime-relevant information generated by a driver.
- This should in large replace all of this information from the old `QMolecule` class.
- This class should provide a `get_second_quantized_op()` method which is capable of converting the integrals generated by a driver into a `SecondQuantizedOp`.
- In order for the above to work we need to mirror the fermionic and bosonic differentiation of the drivers. Thus, we need: `BaseDriverResult`, `FermionicDriverResult` and `BosonicDriverResult` classes.

Points open for discussion:
- it is not yet clear where we will add the `WatsonHamiltonian` and `BosonicBasis` classes into Qiskit Nature. Since these are mainly auxiliary objects for the bosonic case, I think these are coupled to the `BosonicDriver` implementations that we have.
- I am open for suggestions on how to handle this specific case.

**Comment by manoelmarques** [comment]
Creator: @woodsp-ibm

I put this is aqua-core channel, having seen qiskit-nature-core got archived, but moved it out here as I had not seen this issue at the time.

...

In regards of QMolecule - the design there was to accommodate driver output in a driver independent way. It is self-contained (does not import from aqua) as its used to transfer data, via the hdf5 file, from PSI4 process back to Aqua/Chemistry Python process. As such its still needed for this role. It had the broader role of being the common format we used for driver output no matter the driver.

Now I talked about having some DriverResult object that has methods to return the 2nd Q Ops that are proposed (rather than driver run directly returning 2nd Q Ops as is shown in Dec's design pdf), with a view to still having access to the data from the QMolecule since its useful for research in various ways that can still be done outside of the 2nd Q Op stack etc. For instance Atomic Orbitals were used from some research in how to work better to include aspects of molecular symmetries. Anyway my thought here is to rename/refactor QMolecule to say RawDriverData and keep it as a class in its own right. This raw driver data could then be held as an instance inside the DriverResult and accessible via a raw driver data property/method. It has the advantage this way that most of the methods then on DriverResult are around functionality of the stack, getting 2nD Q ops etc. with one method to access the raw data object, that itself has access, in a driver independent way, to integrals, coeffs etc etc. Some methods, like the int conversion to spin coeffs, can be moved out as private support methods in DriverResult leaving the data object as just the driver output. This will allow the HDF5 driver to still work off a stored RawDriverData file so that functionality can be retained as its highly useful too.

**Comment by manoelmarques** [comment]
Creator: @woodsp-ibm

> This class should provide a get_second_quantized_op() method which is capable of converting the integrals generated by a driver into a SecondQuantizedOp.

It needs multiple calls I think. One for energy hamiltonian, 3 for dipoles (X, Y and Z), and we talked about having them there for Spin, Num Particle, Magnetization operators too

**Comment by manoelmarques** [comment]
Creator: @mrossinek

> rename/refactor QMolecule to say RawDriverData

I think that sounds like a good suggestion.

> It needs multiple calls I think. One for energy hamiltonian, 3 for dipoles (X, Y and Z), and we talked about having them there for Spin, Num Particle, Magnetization operators too

Yes, I was not being as verbose this morning as I was about to run late for another meeting :sweat_smile:

**Comment by manoelmarques** [comment]
Creator: @woodsp-ibm

Looking at #21 what I called the RawDriverData above is perhaps more for fermionic drivers versus some raw data entity for bosonic drivers. Though in the latter case its harder to think about common since we only have the one driver based on Gaussian. But maybe whatever the bosonic raw data is it could include this WatsonHamiltonian aspect? although it its kinda of a derived quantity so I do not have enough insight to say whether what is there as the really raw data should go directly to a 2nd Q Op or have that as an intermediary. To me though it seems a parallel level construct in some ways to the spin orbital coeff arrays that are created from the raw driver output in the fermionic case.

**Comment by mrossinek** [comment]
For the first release of qiskit-nature we will leave the existing drivers and `QMolecule` classes mainly untouched. The refactoring work which was done during the move from qiskit-aqua/chemistry to here has isolated this part of the code into a state where we can more or less easily refactor it at a later point in time. Closing this for now.
