### ISSUE TITLE
The GroundStateEigensolver is excruciatingly slow on the IBM Quantum Lab

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/qiskit-nature#500]
### What is the expected enhancement?

Though this may well be a Quantum Lab issue, I'd like to let you comment on it first.

Here is an excerpt of the code from the tutorial here https://qiskit.org/documentation/nature/tutorials/03_ground_state_solvers.html

```
# Test case 1: real quantum hardware - slower
# vqe_solver = VQEUCCFactory(least_busy(IBMQ.load_account().backends(simulator=False, filters=lambda b: b.configuration().n_qubits >= 4)))

# Test case 2: simulator - faster
vqe_solver = VQEUCCFactory(QuantumInstance(backend=Aer.get_backend("aer_simulator_statevector"), shots=4000))

calc = GroundStateEigensolver(QubitConverter(JordanWignerMapper()), vqe_solver)
molecule = Molecule(geometry=[["H", [0.0, 0.0, 0.0]], ["H", [0.0, 0.0, 0.735]]], charge=0, multiplicity=1)
es_problem = ElectronicStructureProblem(ElectronicStructureMoleculeDriver(molecule, basis="sto3g", driver_type=ElectronicStructureDriverType.PYSCF))

res = calc.solve(es_problem)
```

When the simulator `aer_simulator_statevector` is used, the whole thing will be done in 3 seconds.

When the real IBM quantum hardware, e.g., `ibmq_bogota` from the `IBMQ.load_account().backends()` is used, one iteration of the solver will take 25 seconds. I am not talking about the time spent on waiting in the queue. The attached screenshot shows the actual running time is too long.

![too_slow](https://user-images.githubusercontent.com/54299975/148705803-2de494de-17fd-4ae7-a72d-ff006c57dbc3.png)

The real quantum hardware is supposed to be much faster than any classical simulators. That is the whole point of using the quantum computers in the IBM Quantum Lab, isn't it?

**Comment by HuangJunye** [comment]
As far as I know, this is not something we can improve in qiskit-nature but in the whole stack of executing quantum circuits / programs on IBM Quantum. A new metric, Circuit Layer Operation Per Second (CLOPS), to benchmark execution of quantum circuits was introduced by IBM Quantum last year: blog (https://research.ibm.com/blog/circuit-layer-operations-per-second), paper (https://arxiv.org/abs/2110.14108). 

You can find CLOPS for IBM Quantum Systems in this page: https://quantum-computing.ibm.com/services?services=systems As CLOPS get improved, you can expect to see shorten execution time for each iteration. You can also test by changing ibmq_bogota (2.3K CLOPS) to ibmq_manila (2.8K CLOPS), which should give you a slightly shorter execution time.

**Comment by HuangJunye** [comment]
As this is an issue for qiskit-nature, I would suggest to close it.

**Comment by mrossinek** [comment]
Thanks, @HuangJunye, for the explanations above. I agree with your comments.

@DevelopDaily you should also keep in mind that you are testing this on a __very__ small system. H2 in the STO-3G basis with the JW mapper results in a 4-qubit Hamiltonian. Thus, the classical solution of this system is indeed very fast.
