### ISSUE TITLE
same_spin_doubles works incorrectly in UCCSD

### ISSUE THREAD

**Issue by MariaSapova** [Qiskit/qiskit-nature#51]
### Information

- **Qiskit Aqua version**: qiskit-master
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is the current behavior?

`same_spin_doubles = True` in UCCSD variational form does not work correctly, when only beta same spin double excitations are required.

### Steps to reproduce the problem

I faced this problem with triplet O2 molecule. For alpha orbitals there is only one unoccupied spin-orbital, while for beta there are three. I'm expecting to have same spin double excitations only for beta orbitals. However, there are no such excitations when `same_spin_doubles = True`.

### Suggested solutions
Change condition [here](https://github.com/Qiskit/qiskit-aqua/blob/4768635d9a4f467dff035999f4734edb601b1a2c/qiskit/chemistry/components/variational_forms/uccsd.py#L620). When this condition is False due to alpha orbitals, beta сondition is omitted. My solution is:
```
        if same_spin_doubles:
            if len(active_occ_list_alpha) > 1 and len(active_unocc_list_alpha) > 1:
                for i, occ_alpha in enumerate(active_occ_list_alpha[:-1]):
                    for j, unocc_alpha in enumerate(active_unocc_list_alpha[:-1]):
                        for occ_alpha_1 in active_occ_list_alpha[i + 1:]:
                            for unocc_alpha_1 in active_unocc_list_alpha[j + 1:]:
                                double_excitations.append([occ_alpha, unocc_alpha,
                                                           occ_alpha_1, unocc_alpha_1])

            up_active_occ_list = active_occ_list_beta
            up_active_unocc_list = active_unocc_list_beta

            if len(active_occ_list_beta) > 1 and len(active_unocc_list_beta) > 1:        
                for i, occ_beta in enumerate(up_active_occ_list[:-1]):
                    for j, unocc_beta in enumerate(up_active_unocc_list[:-1]):
                        for occ_beta_1 in up_active_occ_list[i + 1:]:
                            for unocc_beta_1 in up_active_unocc_list[j + 1:]:
                                double_excitations.append([occ_beta, unocc_beta,
                                                           occ_beta_1, unocc_beta_1])
```

**Comment by mrossinek** [comment]
Hi @MariaSapova! In #57 I started to take some notes about `UCCSD`. Before the next release we need to refactor it and we will take your proposal from here into account while doing so :+1:

**Comment by mrossinek** [comment]
Hi @MariaSapova! We have made some progress on the refactoring of `UCCSD` in #66. Could you please confirm that the following fixes this issue?

The old `UCCSD` class produces the following list of double excitations for a system which matches your described scenario:
```python
# UCCSD(10, (4, 2), excitation_type='d', same_spin_doubles=True)._double_excitations
[[0, 4, 5, 7],
 [0, 4, 5, 8],
 [0, 4, 5, 9],
 [0, 4, 6, 7],
 [0, 4, 6, 8],
 [0, 4, 6, 9],
 [1, 4, 5, 7],
 [1, 4, 5, 8],
 [1, 4, 5, 9],
 [1, 4, 6, 7],
 [1, 4, 6, 8],
 [1, 4, 6, 9],
 [2, 4, 5, 7],
 [2, 4, 5, 8],
 [2, 4, 5, 9],
 [2, 4, 6, 7],
 [2, 4, 6, 8],
 [2, 4, 6, 9],
 [3, 4, 5, 7],
 [3, 4, 5, 8],
 [3, 4, 5, 9],
 [3, 4, 6, 7],
 [3, 4, 6, 8],
 [3, 4, 6, 9]]
```

As you have described correctly, this is wrong. And in fact, `same_spin_doubles=False` produces an identical list.

Instead, the new code now produces the following excitations:
```python
# build_excitation_ops(2, 10, (4, 2))
[(0, 4), (5, 7)]
[(0, 4), (5, 8)]
[(0, 4), (5, 9)]
[(0, 4), (6, 7)]
[(0, 4), (6, 8)]
[(0, 4), (6, 9)]
[(1, 4), (5, 7)]
[(1, 4), (5, 8)]
[(1, 4), (5, 9)]
[(1, 4), (6, 7)]
[(1, 4), (6, 8)]
[(1, 4), (6, 9)]
[(2, 4), (5, 7)]
[(2, 4), (5, 8)]
[(2, 4), (5, 9)]
[(2, 4), (6, 7)]
[(2, 4), (6, 8)]
[(2, 4), (6, 9)]
[(3, 4), (5, 7)]
[(3, 4), (5, 8)]
[(3, 4), (5, 9)]
[(3, 4), (6, 7)]
[(3, 4), (6, 8)]
[(3, 4), (6, 9)]
# The following are new (and should be the ones you missed):
[(5, 7), (6, 8)]
[(5, 7), (6, 9)]
[(5, 8), (6, 7)]
[(5, 8), (6, 9)]
[(5, 9), (6, 7)]
[(5, 9), (6, 8)]
```

Please confirm that this issue is solved by the addition of the extra excitations at the end of this list.

The `same_spin_doubles=False` case can be reproduced by adding the keyword argument `max_spin_excitation=1` to the `build_excitation_ops` method call.

**Comment by MariaSapova** [comment]
@mrossinek what about pairs of excitations like [(5, 7), (6, 8)] and [(5, 8), (6, 7)]? Aren't they the same because electrons are indistinguishable?

**Comment by mrossinek** [comment]
> what about pairs of excitations like [(5, 7), (6, 8)] and [(5, 8), (6, 7)]? Aren't they the same because electrons are indistinguishable?

This is being dealt with later in the code :+1:

**Comment by mrossinek** [comment]
Actually you are right, this is not being dealt with... Thanks for raising this! I will look into it right away :+1:

**Comment by mrossinek** [comment]
Alright I just pushed a fix and the only new excitations are now the following:
```
((5, 7), (6, 8))
((5, 7), (6, 9))
((5, 8), (6, 9))
```

**Comment by MariaSapova** [comment]
@mrossinek Now it looks fine. I think the issue is solved. Thank you!
