### ISSUE TITLE
Cannot import thermodynamic properties

### ISSUE THREAD

**Issue by Janez88** [Qiskit/qiskit-nature#528]
### Environment

- **Qiskit Nature version**: 0.3.0
- **Python version**: 3.7
- **Operating system**: Windows and Linux

### What is happening?

Cannot import thermodynamic properties from qiskit-nature/docs/tutorials/thermodynamics_utils. Always get ModuleNotFoundError. 

### How can we reproduce the issue?

`from thermodynamics_utils.thermodynamics import constant_volume_heat_capacity
from thermodynamics_utils.vibrational_structure_fd import VibrationalStructure1DFD
from thermodynamics_utils.partition_function import DiatomicPartitionFunction
from thermodynamics_utils.thermodynamics import Thermodynamics
ModuleNotFoundError                       Traceback (most recent call last)`

### What should happen?

I should be able to import all the properties, but I always get the traceback

### Any suggestions?

Put the properties into different module.

**Comment by mrossinek** [comment]
In what scenario are you running into this issue? If you are trying to run the tutorial this is a bug. If you are trying to import these utilities from a custom script than this is not a bug.
The reason that the thermodynamic utilities are not exposed as part of Qiskit Nature itself, is that they are by no means generalized enough to work predictably for usage outside of the tutorial. If you really do want to use them you would need to manually add the required path to `sys.path` (discouraged) or extract the code you need manually.

@pbark probably has some more insight on this
