### ISSUE TITLE
Add 'frozen_extracted_energy' to BOPESSampler

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#54]
See also Qiskit/qiskit-aqua#1486 

I did not transfer the issue since there is a PR with a pending fix. There is an issue around PH energy extracted too as I noted that is not catered to. Also with the chemistry code refactor here the 'fix' may end up looking different but whatever the refactor entails the current bug around the extracted energies needs to be corrected, hence this issue.

**Comment by mrossinek** [comment]
I have a fix in mind as mentioned [here](https://github.com/Qiskit/qiskit-aqua/pull/1490#issuecomment-803884976).
We can address this once #83 is closed (or in the process of doing so).
