### ISSUE TITLE
Jordan Wigner transform requires too much boilerplate

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#540]
### What is the expected enhancement?

This is how I have been doing the Jordan-Wigner transform to convert a FermionicOp to a SparsePauliOp:

```python
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.mappers.second_quantization import JordanWignerMapper

transformed_op = QubitConverter(mapper=JordanWignerMapper()).convert(operator).primitive
```

Instead, I would like to do something like
```python
from qiskit_nature import jordan_wigner

transformed_op = jordan_wigner(operator)
```

**Comment by mrossinek** [comment]
When Nature was split out of Aqua we have decided to take a much more modular
approach to the development. This immediately also brought in very verbose
import paths which can be (admittedly) cumbersome to type out.

However, as an uninitiated user you can learn a lot more from
```
from qiskit_nature.mappers.second_quantization import JordanWignerMapper
```
than from
```
from qiskit_nature import jordan_wigner
```

The latter hides major aspects of the stack and, on top of that, would add a
redundancy of how a certain operation is performed which is generally a bad
idea.
For personal use, such a wrapper may be fine but I do not think that it is a
good approach for educating users and application developers. Instead,
explicitly embracing the modularity is useful to both new users/researchers and
stack developers.

Finally, for the specific case of the JW mapping, you do not need to use the
`QubitConverter` and instead can use the following directly:
```
from qiskit_nature.mappers.second_quantization import JordanWignerMapper

transformed_op = JordanWignerMapper().map(operator)
```

**Comment by kevinsung** [comment]
I'm mainly talking about the length of the code itself, not the imports. But thanks for the explanation of that, it's good to know.

>Finally, for the specific case of the JW mapping, you do not need to use the
QubitConverter and instead can use the following directly:

Thanks, I didn't know that. This is better, but in my opinion it is still a bit too verbose. It would be nice to have it be a simple function call, without requiring the initialization of a separate object.

**Comment by mrossinek** [comment]
It's easy enough to define that function yourself when you find yourself using it so often. I don't think this grants a redundant option in the code base.
