### ISSUE TITLE
Hamiltonian Variational Form (TASP)

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#55]
See Qiskit/qiskit-aqua#703 which was a draft PR to added a Hamiltonian Variational Form (or Trotterized Adiabatic State Preparation, TASP) .

What might be nice to have is a base class for an ansatz that is built from evolving operators. Maybe this base class ends up in qiskit circuit library. It could potentially be used as base for QAOA ansatz, UCCSD etc. And also to provide an ansatz as per the linked draft PR.

**Comment by mrossinek** [comment]
Hi Steve! To what degree do we cover this in #66? Can we consider that PR to also be closing this issue? Or do we need/want another (potentially very similar) class which implements the proposed `TASP` in a form where you pass in any operator which will be evolved? @Cryoris this is probably what the `EvolvedOpAnsatz` does to a large degree, correct?

**Comment by woodsp-ibm** [comment]
I think that #66 should cover it. I made comment about initial_state in `EvolvedOperatorAnsatz` but as you say that looks it would accommodate what was shown in that draft PR raised on Aqua.
