### ISSUE TITLE
Normal order should reduce, not the other way around

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#551]
### Environment

- **Qiskit Nature version**: 98de3b06fbc8b03e4079fbf7e256169f0196facc
- **Python version**: N/A
- **Operating system**: N/A

### What is happening?

Normal ordering should put an operator into a canonical form. This means that two equivalent operators should have the same normal order. So `FermionicOp.to_normal_order` should "reduce" the operator by merging terms with the same label. It currently does not do this.

Reducing an operator should refer to merging terms with the same label. This is a useful operation in itself. It should not perform normal ordering, which takes exponential time in general. Reducing should be efficient. Currently, reducing a FermionicOp normal orders it, which is incorrect behavior.

### How can we reproduce the issue?

```python
import random
from qiskit_nature.operators.second_quantization import FermionicOp

random.seed(123)
k = 50
n = 100

op = sum(
    (FermionicOp(''.join(random.choices('+-ENI', k=k)), display_format="dense") * random.random())
    for _ in range(n))
op.reduce()
```

### What should happen?

This operation should complete in at most a few seconds, probably under one second. Instead, it takes a very long time (I have not witnessed it complete, so I don't know how long).

### Any suggestions?

`FermionicOp.to_normal_order` should normal order and reduce, and `FermionicOp.reduce` should only reduce (not normal order).

**Comment by jlapeyre** [comment]
After a brief look, I agree at least in part. It should be possible to collect terms without doing an expensive, unrelated operation.

**Comment by pbark** [comment]
@kevinsung thanks for pointing this out. I agree with your evaluation. The fix should not be very difficult. Would you be open to tackle this?

**Comment by kevinsung** [comment]
@pbark Sure, I can fix this. I would like to take this opportunity to rename these methods. If we do that, then we can keep the old ones for one deprecation cycle; otherwise they would break immediately in the next release. I think the names can be improved in the following ways:
1. Rename `reduce` to `simplify`. This would align it with `SparsePauliOp` from Qiskit Terra which reduces the need for the programmer to remember two different names for the same operation.
2. Rename `to_normal_order` to `normal_ordered`. The reason to make this change is that usually methods named `to_X` return an object of a different type, which is not the case here. For example, `to_array`, `to_matrix`, `to_fermionic_op`, etc.

What do you think?

**Comment by ikkoham** [comment]
> Rename reduce to simplify. This would align it with SparsePauliOp from Qiskit Terra which eliminates the need for the programmer to remember two different names for the same operation.

`reduce` is same with opflow. Perhaps the major difference will be in the future that reduce includes the order sort and simplify does not.

**Comment by kevinsung** [comment]
@ikkoham The docstring of `reduce` says
```
`Reduce` merges terms with same labels and chops terms with coefficients close to 0.
```
So normal-ordering the operator is actually incorrect behavior according to this. Besides, there's no need for one function to both simplify and normal-order, and it's better to have just one way of doing it.

>`reduce` is same with opflow.

This is unfortunate.

**Comment by ikkoham** [comment]
@kevinsung I agree with you. If new simplify does not sort the order, it would be nice to have the name `simplify`.
In Terra, there is a move to exclude n log(n) computationally expensive sorts from simplify. So, I think this direction is correct :+1:

**Comment by kevinsung** [comment]
Ok I'll go ahead then. Just to be clear, the agreed changes are:
1. Add `simplify` and deprecate `reduce`.
2. Add `normal_ordered` and deprecate `to_normal_order`.

**Comment by kevinsung** [comment]
Actually, `simplified` is a better name because the method returns a copy rather than modifying the operator in place. But we'd need to use `simplify` to be consistent with `SparsePauliOp`. But then the tense would be inconsistent with `normal_ordered`. Unfortunate...
