### ISSUE TITLE
Formatting check fails to ignore build files

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#567]
### Environment

- **Qiskit Nature version**: 47eabdb07cc68cbe28fdb4140c6a878cb18d76f9
- **Python version**: 3.9.6
- **Operating system**: RHEL 8.5

### What is happening?

Running local checks produces error on black check.

### How can we reproduce the issue?

Run `make all_check`
```
...
python -m black --check --exclude="gauopen" qiskit_nature test tools docs
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.operators.second_quantization.FermionicOp.ipynb
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.operators.second_quantization.FermionicOp.py
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.operators.second_quantization.SpinOp.ipynb
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.problems.second_quantization.lattice.HyperCubicLattice.ipynb
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.operators.second_quantization.SpinOp.py
would reformat docs/_build/jupyter_execute/stubs/qiskit_nature.problems.second_quantization.lattice.HyperCubicLattice.py
Oh no! 💥 💔 💥
6 files would be reformatted, 426 files would be left unchanged.
make: *** [Makefile:50: style] Error 1
```

### What should happen?

No error.

**Comment by mtreinish** [comment]
This looks like your running black on the wrong files by mistake. The files in `_build/jupyter_execute` are almost certainly generated content by `jupyter-execute` directives that sphinx is generating after compiling the documentation. There isn't any reason you should need to run code formatting on them as they're not source code in the repository.

**Comment by kevinsung** [comment]
Thanks, I've updated the title of this issue accordingly.
