### ISSUE TITLE
Refactor UCCSD

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#57]
### What is the expected enhancement?

`UCCSD` needs to be refactored for several reasons:
- it is incompatible with the `VQE` implementation provided by Qiskit Terra
- it uses the (soon-to-be-removed) `FermionicOperator` class
- it uses the legacy `WeightedPauliOperator`

The following requirements should be met by the new implementation:
- it should derive `BlueprintCircuit` and, thus, be compatible with Terra
- the hopping operator factory logic should be moved to an external place as it can also be of use elsewhere (currently `FermionicTransformation` actually uses the logic inside of UCCSD)
- it should make use of the new `FermionicOp` and opflow operators
- ideally, the hopping operator factory should be generalized to work for any kind of exctitation (`S`, `D`, `T`, `Q`, ...)
- ideally, we would have a `UCC` class in which the user can freely specify the types of excitations he would like to have
- (we may provide ease-of-use subclasses like `UCCSD`, `UCCD`, etc.)

Once `UCCSD` has been refactored we should also be able to replace all `qiskit.aqua` imports with their new counterparts. Thus, the `critical` status of this issue.

**Comment by mrossinek** [comment]
I did some preliminary thinking on how one could implement a generic factory method to construct a list of excitation operators:
```python
def build_excitation_ops(num_excitations: int, num_orbitals: int, num_particles: Tuple[int]):
    """Builds all possible excitation operators with the given number of excitations for the
    specified number of particles distributed in the number of orbitals.

    Args:
        num_excitations: number of excitations per operator (1 means single excitations, etc.).
        num_orbitals: number of spin-orbitals.
        num_particles: number of alpha and beta particles.
    """
    # generate sets of alpha-spin orbital indices for occupied and unoccupied ones
    set_alpha_occ = set(range(num_particles[0]))
    set_alpha_unocc = set(range(num_particles[0], num_orbitals // 2))
    # the cartesian product of these sets gives all possible single alpha-spin excitations
    alpha_excitations = set(itertools.product(set_alpha_occ, set_alpha_unocc))

    # generate sets of beta-spin orbital indices for occupied and unoccupied ones
    set_beta_occ = set(range(num_orbitals // 2, num_particles[1] + num_orbitals // 2))
    set_beta_unocc = set(range(num_orbitals // 2 + num_particles[1], num_orbitals))
    # the cartesian product of these sets gives all possible single beta-spin excitations
    beta_excitations = set(itertools.product(set_beta_occ, set_beta_unocc))

    excitations = set()
    # we can find the actual list of excitations by doing the following:
    #   1. combine the sets of single alpha- and beta-spin excitations
    #   2. find all possible combinations of length `num_excitations`
    #   3. only use those where all indices are unique
    for comb in itertools.combinations(alpha_excitations | beta_excitations, num_excitations):
        # validate a combination by asserting that all indices are unique:
        #   1. flatten the tuple of tuples (chain.from_iterable)
        #   2. the length equals twice the number of excitations (one excitation gives to indices)
        if len(set(itertools.chain.from_iterable(comb))) == num_excitations * 2:
            # we zip the tuple of tuples to obtain a new one which has the structure:
            #   ((occupied indices), (unoccupied indices))
            excitations.add(tuple(zip(*comb)))

    # Some notes in terms of customization:
    #   - which excitations are present can (obviously) be configured via `num_excitations`
    #   - we can add an option to limit it to only `alpha` or only `beta` easily
    #   - if we want both spin kinds but no cross terms (i.e. pure spin excitations), we need to
    #   construct the excitation list in two separate steps. First only alpha, then only beta. But
    #   this is also easy to adjust.

    for exc in excitations:
        label = ['I'] * num_orbitals
        for occ in exc[0]:
            label[occ] = '-'
        for unocc in exc[1]:
            label[unocc] = '+'
        label = ''.join(label)
        print(exc, label)
```

**Comment by woodsp-ibm** [comment]
See also #55

**Comment by woodsp-ibm** [comment]
> Once UCCSD has been refactored we should also be able to replace all qiskit.aqua imports with their new counterparts. Thus, the critical status of this issue.

I think additionally there is of other code being tested here that depends on FermionicOperator, which in turn depends on current Aqua repo for legacy operators. Since there are modules here that are not wanted maybe they, and their unit tests, could be deleted now (they exist in Aqua so they can be easily referred to if wanted). That would reduce a bunch of dependency on Aqua that does not exist in Terra repo. Then if you want to be running this off Terra asap, since that would since that would render UCCSD inoperable ahead of it being refactored, simply disable any tests temporarily that use this until its done. Though I do see quite a lot of tests where its used.

> the hopping operator factory logic should be moved to an external place as it can also be of use elsewhere...

Potentially the same thing for the excitation list computation as that has been used elsewhere too.

**Comment by woodsp-ibm** [comment]
Given there is an active space transformer now; do we still want to keep the active space setting capability in UCCSD that further limits things. We had both in the past but it always seemed more efficient to remove the orbitals from the operator if they not used as it took less qubits. If its kept here maybe the way its expressed needs to look more like the active space transformer configuration?

**Comment by woodsp-ibm** [comment]
For the hopping operator logic above, with num orbitials and num particles, this is akin to logic we used in the past where the occupancy was known to be the lower orbitals given they were arranged in order. As your active space transforms runs from an occupancy array, since you wanted to be able to have systems that did not fit the current occupancy assumption, then maybe we should be setting up any new APIs based on this premise even if initially the occupancy does conform to the current assumption.

**Comment by mrossinek** [comment]
> I think additionally there is of other code being tested here that depends on FermionicOperator

I was going to suggest removing all of those once #49 is merged.

> Potentially the same thing for the excitation list computation as that has been used elsewhere too.

Yes, I consider these things linked.

> maybe we should be setting up any new APIs based on this premise even if initially the occupancy does conform to the current assumption.

Yes, that sounds like a good idea! Although we can also get a basic version with the current assumptions in place working first, and later on extend it to the more general case.

**Comment by Cryoris** [comment]
Summarizing use cases from the discussion we had (modulo correct class and argument names):
```python
# case 1
gse = GroundStateEigensolver(UCCSDVQEFactory(), mapper)
gse.solve(molecular_problem)

# case 2
h2 = (I ^ I) + (Z ^ Z) + ...  # copy my hamiltonian from somewhere or construct it manually

uccsd = UCCSD(4, 2, mapper, symmetry_info)  # put in proper mapper and symmetry info
vqe = VQE(uccsd, optimizer)
vqe.compute_min_eigenvalue(h2)


# case 3
class MyFactory():
    # uccsd = UCCSD()
    # vqe = VQE(uccsd, optimizer)

gse = GroundStateEigensolver(MyFactory(), mapper)
gse.solve(molecular_problem)
```
and the proposed circuit structure:
```python

class EvolvedOperatorAnsatz(BlueprintCircuit):
    """
    Examples:
        excitations = build_excitation_ops(num_part, num_orb)
        mapper = Mapper()
        mapped_excitations = mapper.map(excitations)
        # and other postproc

        ucc = EvolvedOperatorAnsatz(mapped_excitations)
    """
    def __init__(self, ops=None, evolution=None):
        pass

class UCC(EvolvedOperatorAnsatz):
    """
    Examples:
        ucc = UCC('sdt', num_part, num_orb, mapper)

        excitations = build_excitation_ops(num_part, num_orb, 'sdt')
        ucc = UCC(excitations, mapper)
    """
    def __init__(self, excitations=None, num_part=None, num_orb=None, mapper=None):
        pass

class UCCSD(UCC):
    def __init__(self, num_part=None, num_orb=None, mapper=None):
        super().__init__('sd', num_part, num_orb, mapper)
```

**Comment by mrossinek** [comment]
@Cryoris and I started to look into the old code of UCCSD and figure out where everything needs to be moved in order to comply with the proposal above. We took notes in a separately shared Box Note of which I will include some screenshots below (its simpler than trying to reformat everything here).

First, an overview of the current init arguments and methods of the `UCCSD` class:
![screenshot_1614352558](https://user-images.githubusercontent.com/21973473/109318391-07e28500-784e-11eb-813a-8eeb8db418f3.png)

Then, an overview of the classes which we propose to implement:
![screenshot_1614352574](https://user-images.githubusercontent.com/21973473/109318422-116bed00-784e-11eb-8622-01931e9b572c.png)

I also drafted these classes and will push them to a branch in a second. I will open a draft PR and link to this issue so that we can collaborate and continue the discussion there, too :+1:

**Comment by woodsp-ibm** [comment]
This refactor should also include the [UVCC](https://github.com/Qiskit/qiskit-nature/blob/master/qiskit_nature/components/variational_forms/uvcc.py) var form too right that was done for Bosonic Problems. I think the same EvolvedOp base class should be usable for this, but it needs bosonic hopping operators; so maybe we need to be careful about naming of the excitation and hopping logic above to differentiate things.
