### ISSUE TITLE
VQE initial point when using HF+UCC

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#571]
### What is the expected enhancement?

When creating an initial_state + variable anstaz combined state in order to have HF+UCCSD produce the HF energy as the first eval the ansatz, in this case UCCSD needs to be appropriately parameterized. All zeros in this case. Now there still remains in the EvolvedOperatorAnstaz a preferred init point method where the idea was to inform VQE (or any other algo that might need it) of this parameterization such that it could be used for cases where the user did not explicitly supply an initial point and using a random point was not desired. See https://github.com/Qiskit/qiskit-terra/blob/a6cb1a37f52fd98f90d0685d1fdcba447a5345b7/qiskit/circuit/library/evolved_operator_ansatz.py#L139-L153

This mechanism had problems in applying it in general across the ansatzes, and this remains as the last vestige of that logic that still kinda works. So give VQE the UCCSD+HF and lo and behold it the first eval is the HF energy... but gotcha first transpile the HF+UCCSD and give it the transpiled circuit and it does not. The difference is that the result of transpilation is no longer the UCC sub-class of QuantumCircuit and its does not have the special method. This method is looked for by VQE in its path where the initial point is not given explicitly. If this method exists then it gets the special (preferred) start point, otherwise its random and this is the case here.

As the above linked code shows it has long been desired for something better/different. One thought is to document the initial point of all zeros in UCC and require the user, when directly using VQE + HF+UCC to explicitly set it. By doing this it does not matter whether you use a transpiled version or original it would all work - no magic implicit stuff going on in background - though VQE does state this is what it does https://github.com/Qiskit/qiskit-terra/blob/a6cb1a37f52fd98f90d0685d1fdcba447a5345b7/qiskit/algorithms/minimum_eigen_solvers/vqe.py#L103-L105 Of course knowing which ansatzes do/don't have that capability is more of a challenge. 

To keep some of 'the magic' what could be done is that the VQE + UCC factories could take care of the initial point on behalf of the user so at it gets set as we do things today. Drop down though to using VQE and UCC directly though you would be charged with the initial point yourself just like any other say heuristic anstazes we have where they have no preferred point.

It is of course possible to deprecate the current behavior warning that if we set all zeros automatically this way that it will be required that the user do it explicitly in the future.

Perhaps there are other ways. The above describes though the area that this ought to address and outlines some initial thought.

**Comment by Cryoris** [comment]
If I use just a UCCSD ansatz and plug that into the VQE the HF initial state is not automatically added, is it? In that scenario it seems to me that the all-zero initial state might be attached to the wrong object. 

Running VQE with HF+UCCSD, and initializing it with the correct state, could also be considered a full workflow where the user doesn't really have to deal with our basic building blocks anymore. Couldn't we define an "application" for this? That could be a wrapper around VQE where you only provide an operator (maybe in 2nd quantization?) and it'll run HF+UCC for you. 

But I'm also a bit biased towards removing the `preferred_init_points` since it's a logic we globally added to ansatz circuits and the VQE but it is only used for the specific case of HF+UCCSD.

**Comment by mrossinek** [comment]
> Running VQE with HF+UCCSD, and initializing it with the correct state, could also be considered a full workflow

This is exactly what the `VQEUCCFactory` does. In that scenario everything works as expected and we are also able to simply set `VQE.initial_point` manually as desired (i.e. there is no need for the `preferred_init_points`).

However, the problem arises when a user does things manually _and_ transpiles the ansatz themselves. When they pass the blueprint (HF+UCC) into the `VQE` things still work as expected because the `EvolvedOperatorAnsatz` specifies the all-zero init point.
But when transpiling manually this information gets lost when the raw `QuantumCircuit` gets constructed.

**Comment by Cryoris** [comment]
If we would remove `preferred_init_points` then the expectation would never be that VQE/UCC sets the initial points for you, so no matter whether you transpile or not -- you have to set the initial point yourself. In this case, no expectations are broken 😉 

And if you do want to have things set for you, you can use `VQEUCCFactory` 😄

**Comment by mrossinek** [comment]
Yes that's exactly the conclusion which we have arrived at as well.

This would require:
- removing `preferred_init_points` (also in the docs of `VQE.init_point`)
- fixing the initialization in `VQEUCCFactory`
- properly documenting the expectation for a user to manually set the `init_point` (I suggested to @woodsp-ibm offline that we could even point to the `VQEUCCFactory` as a "reference setup" from the UCC docs)

**Comment by mrossinek** [comment]
I just looked over this issue again, and I believe that from the Nature-side of things, this should now be considered resolved, correct?
That means, all that is left to close this issue, is to open a PR to Terra which removes the concept of the `preferred_init_point` from the `EvolvedOperatorAnsatz` and `VQE` (and anywhere else it may occur).

How should we handle this in terms of "deprecation"? Terra will obviously need to deprecate this. But how can we inform the Nature users, that using the new `InitialPoint` classes will become a requirement?

**Comment by Cryoris** [comment]
Could we put a that information in the deprecation warning in the circuits and say that if used for a `GroundStateSolver` or so one should use `InitialPoint`?

**Comment by mrossinek** [comment]
> Could we put a that information in the deprecation warning in the circuits and say that if used for a `GroundStateSolver` or so one should use `InitialPoint`?

This could be an option if Terra is willing to have Nature-specific information in their deprecation warning

**Comment by woodsp-ibm** [comment]
The InitialPoint is defaulted in the factories in Nature right and its only for factories. That is translated, so to speak, to the initial parameterization of the anstaz, which when used with VQE we start the optimizer at a point as given by the user or a random choice. So its only if you do things without a factory when say using UCCSD. Though I do not think there is anything wrong as such with a different point, it may even be a lucky guess thats it a better starting point than the HF state say. Since UCC has an initial state as a parameter maybe something can be said in the docstring with that there so if you use UCC directly yourself and are just looking at its docs then it perhaps mentioning initial parameterization and algos like VQE, or however its worded. For example that indicates InitialPoint when using factory and suggests setting it otherwise manually, for which you will need to configure VQE after fully configuring UCC in order to know how many parameters and hence set them.
