### ISSUE TITLE
Support additional data in `DriverMetadata`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#574]
### What is the expected enhancement?

#573 adds a workaround for the `DriverMetadata` object when passed through a transformer.

A useful enhancement would be to support additional data in this container which can store transformer-related information. This would serve the purpose of providing full information of how a certain driver result was obtained aiding in future reproducability.

A very crude idea would be to add string representations of the transformer instances which were applied to a given driver result. Then `DriverMetadata` could simply store a list of the applied transformers which a user could read and interpret in order to reproduce a certain result.

Here are some more specific implementation ideas:
- [ ] implement `BaseTransformer.__repr__(self)` for all its subclasses
- [ ] add a `DriverMetadata.transformers: List[str]` field and increment it's `VERSION` class attribute (if this get's done after Qiskit Nature 0.4 is released)
- [ ] append the transformers `repr(self)` representation to the `DriverMetadata.transformers` list when transforming this object (see #573 for the code location where this would need to be added)
- [ ] handle `DriverMetadata.transformers` during `to_hdf5` and `from_hdf5` of the `DriverMetadata` class (versioning needs to be handled if the `VERSION` had to be increased)
- [ ] unittest all of the above

**Comment by Zshan0** [comment]
Hey, I'd like to start contributing to `qiskit-nature`, can you please assign this to me? Thanks :D

**Comment by mrossinek** [comment]
I had this issue in my inbox again because somebody left a comment here which now appears to have been deleted.
Nonetheless, I wanted to leave a short update here, stating that the `DriverMetadata` is likely to undergo a significant re-design as part of #701 and #705. Thus, I will mark this issue as requiring more information and highly recommend anyone who would want to start on this, to first check in on the current status of its design :+1:
