### ISSUE TITLE
Heisenberg model

### ISSUE THREAD

**Issue by jvscursulim** [Qiskit/qiskit-nature#577]
### What should we add?

I saw that recently the Ising model was added to Qiskit Nature, this model is a special case of the Heisenberg model (https://en.wikipedia.org/wiki/Quantum_Heisenberg_model). Thus, I would like let you all know that I would like to contribute to Qiskit Nature adding this model, because I have developed a code that implements this model during the Qiskit Advocate Mentorship Program Fall 2021.

**Comment by pbark** [comment]
Hi @jvscursulim ! Thanks for you  interest in contributing to our lattice models! Your contribution is very welcome. 

Please take a look [here](https://github.com/Qiskit/qiskit-nature/blob/main/CONTRIBUTING.md) or  [here](https://qiskit.org/documentation/contributing_to_qiskit.html) about contribution guidelines. 

Looking forward to your PR.

**Comment by jvscursulim** [comment]
Thanks @pbark , I will read the contribution guidelines and I will create the PR as soon as possible.
