### ISSUE TITLE
Tutorial-6: ")" is needed in the equation

### ISSUE THREAD

**Issue by kifumi** [Qiskit/qiskit-nature#593]
### Environment

- **Qiskit Nature version**: 0.3.1
- **Python version**: 
- **Operating system**: macOS Big Sur
- Web-browsing software: Firefox, Chrome

### What is happening?

In the equation of the vibrational partition function, ")" might be needed.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/19249007/157778376-cbf1fa18-fb02-459d-b913-7c9c5d017684.png">

### How can we reproduce the issue?

You can see the [qiskit.org tutorial](https://qiskit.org/documentation/nature/tutorials/06_calculating_thermodynamic_observables.html) or the [notebook on github](https://github.com/Qiskit/qiskit-nature/blob/main/docs/tutorials/06_calculating_thermodynamic_observables.ipynb).

### What should happen?

We should add ")" to the denominator.

**Comment by garrison** [comment]
Thank you for the report.  Please feel free to open a pull request, if you are interested. :slightly_smiling_face:

**Comment by woodsp-ibm** [comment]
Fixed by #598 which has now been merged so closing this.
