### ISSUE TITLE
Not explicitly providing `register_length` argument in initialization of sparse `FermionicOp` results in incorrect expectation values

### ISSUE THREAD

**Issue by JoelHBierman** [Qiskit/qiskit-nature#609]
### Environment

- **Qiskit Nature version**: 0.3.1
- **Python version**: 3.9.5
- **Operating system**: MacOS 12.2.1

### What is happening?

EDIT: Actually on second thoughts, it's not clear to me whether this is actually a bug or just user error, but I have left this up just in case this is not the intended functionality.

Suppose you initialize a sparse `FermionicOp`, but do not explicitly set `register_length=num_qubits`, then in general its expectation value (we're assuming that it's Hermitian here) with respect to a specified state will be incorrect. It's not totally clear to me whether this is a bug with `FermionicOp` or if this just exposes a bug in how Qiskit Terra's Op flow handles expectation values of `PauliSumOp`s, but there is a bug _somewhere_.

### How can we reproduce the issue?

The following code reproduces the bug:

```
from qiskit_nature.drivers import PySCFDriver
from qiskit_nature.problems.second_quantization import ElectronicStructureProblem
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.mappers.second_quantization import JordanWignerMapper
from qiskit_nature.circuit.library import HartreeFock
from qiskit_nature.operators.second_quantization import FermionicOp
from qiskit.utils import QuantumInstance
from qiskit.opflow import CircuitStateFn, AerPauliExpectation, StateFn, CircuitSampler
from qiskit.providers.aer import AerSimulator
from qiskit_nature.drivers import PySCFDriver, UnitsType, Molecule

import numpy as np

interatomic_distance =0.735
basis = 'sto3g'
backend = AerSimulator(method='statevector')
quantum_instance = QuantumInstance(backend=backend, seed_transpiler=1)
molecule = Molecule(geometry=[['H', [0., 0., 0.]],
                            ['H', [0., 0., interatomic_distance]]],
                    charge=0, multiplicity=1)
driver = PySCFDriver(molecule = molecule, unit=UnitsType.ANGSTROM, basis=basis)
q_molecule = driver.run()

qubit_converter = QubitConverter(JordanWignerMapper())
es_problem = ElectronicStructureProblem(driver=driver)
second_q_op = es_problem.second_q_ops()
qubit_op = qubit_converter.convert(second_q_op[0])

num_qubits = 2*q_molecule.num_molecular_orbitals

HF_state = HartreeFock(num_spin_orbitals=num_qubits,
                                                       num_particles=(q_molecule.num_alpha,q_molecule.num_beta),
                                                       qubit_converter=qubit_converter)

ansatz = HF_state
print(HF_state)

op_1 = qubit_converter.convert(FermionicOp(data='+_0 -_0'))
op_2 = qubit_converter.convert(FermionicOp(data='+_0 -_0', register_length=4))
op_3 = qubit_converter.convert(FermionicOp(data='N_0'))
op_4 = qubit_converter.convert(FermionicOp(data='NIII'))
op_5 = qubit_converter.convert(FermionicOp(data='N_0', register_length=4))
op_list = [op_1, op_2, op_3, op_4, op_5]

for op in op_list:
    expectation = AerPauliExpectation()
    observable_meas = expectation.convert(StateFn(op, is_measurement=True))
    ansatz_circuit_op = CircuitStateFn(ansatz)
    expect_op = observable_meas.compose(ansatz_circuit_op).reduce()

    sampled_expect_op = CircuitSampler(backend=backend).convert(expect_op)
    means = sampled_expect_op.eval()
    print(f'Evaluation of operator {op} is: {means}')
    print()
```

I print out the HartreeFock state just as a sanity check to see that the occupation number of orbital 0 in the Jordan Wigner encoding is 1. The output of the for-loop is:

```
Evaluation of operator 0.5 * I
- 0.5 * Z is: 0.0

Evaluation of operator 0.5 * IIII
- 0.5 * IIIZ is: 1.0

Evaluation of operator 0.5 * I
- 0.5 * Z is: 0.0

Evaluation of operator 0.5 * IIII
- 0.5 * IIIZ is: 1.0

Evaluation of operator 0.5 * IIII
- 0.5 * IIIZ is: 1.0    
```

### What should happen?

All of these `FermionicOp`s are equivalent, so their expectation values with respect to the same state should be the same. In this case, the fix from a user's perspective is simple: explicitly set `register_length`, but this still should not happen and could be easily missed in more complicated code where the correct result is not so easily verified.

### Any suggestions?

The issue is either with `FermionicOp` or how Opflow handles expectation values of `PauliSumOp`s where the identity operator is implicit on some of the qubits.

**Comment by mrossinek** [comment]
The reason that you are seeing this discrepancy is because these operators are actually _not_ identical.

Let me try to explain why.

```python
FermionicOp("N_0")
# this results in the qubit operator
0.5 * (I - Z)
# whereas
FermionicOp("N_0", register_length=4)
# will result in
0.5 * ((I ^ I ^ I ^ I) - (I ^ I ^ I ^ Z))
```
If you evaluate the former qubit operator on a circuit with 4 qubit registers, it will get evaluated on the _last_ qubit because Qiskit Terra treats operators as [little endian](https://en.wikipedia.org/wiki/Endianness). Thus, the following are actually equivalent in this setting:
```python
0.5 * (I - Z)
# gets interpreted as
0.5 * ((I ^ I ^ I ^ I) - (Z ^ I ^ I ^ I))
```
The latter you would obtain from `FermionicOp("N_3")` because in Qiskit Nature we treat operators as **big endian**. The reason for this difference is the chemistry-user oriented approach taken by Qiskit Nature where big endian operators are the standard.

I hopes this answers your question. I suggest to avoid confusion that you always explicitly set `register_length` when using sparse labels.
