### ISSUE TITLE
Allow own compilation of Gaussian drivers

### ISSUE THREAD

**Issue by BastianZim** [Qiskit/qiskit-nature#625]
### What is the expected enhancement?

Hi everybody,

this issue is in the context of me adding the package to conda-forge: https://github.com/conda-forge/staged-recipes/pull/18519

The [gaussian drivers](https://github.com/Qiskit/qiskit-nature/tree/main/qiskit_nature/drivers/second_quantization/gaussiand/gauopen) are currently precompiled which makes it difficult for me to add it to conda-forge as we prefer to compile everything ourselves and for our platforms.

Would it be possible to make these optional or allow the user (me) to compile them myself when I compile qiskit-nature?

Thanks!

**Comment by BastianZim** [comment]
Yes that's the one. Ahh ok I did compare the drivers but saw some extra files so I wasn't sure. Then I'll just remove these files before compilation and do it myself. Thanks for the pointers!

Would it be possible to add a flag or env variable to the setup.py that governs this automatically? Just asking because it would make the process slightly easier for me although I can also do it manually and close the issue. If this is out of scope for you.

**Comment by woodsp-ibm** [comment]
The set of files that are included is controlled by the MANIFEST.in file in the root here. So if you did a slightly altered version of that you could omit the line grafting on all the files in the gauopen folder instead of removing them afterwards.

**Comment by BastianZim** [comment]
Ahh true that's a great idea – will do that. Thanks!
