### ISSUE TITLE
TestVibrationalStructureMoleculeDriver in test_molecule_driver fails

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#631]
### Environment

- **Qiskit Nature version**: main branch
- **Python version**: 3.9

### What is happening?

The test is not run in CI as it depends on Gaussian being installed
```
Error
Traceback (most recent call last):
  File "test/drivers/second_quantization/test_molecule_driver.py", line 159, in test_driver
    self._check_driver_result(TestVibrationalStructureMoleculeDriver._MOLECULE_EXPECTED, result)
  File "test/drivers/second_quantization/test_molecule_driver.py", line 140, in _check_driver_result
    for i, entry in enumerate(watson.data):
AttributeError: 'VibrationalStructureDriverResult' object has no attribute 'data'
```

It seems its still referring to old WatsonHamiltonian and trying to access the `data` field it had. But this is no longer the result. In printing the result it shows this
```
VibrationalStructureDriverResult:
	None:
	VibrationalEnergy:
		None
		1-Body Terms:
			<sparse integral list with 13 entries>
			(2, 2) = 352.3005875
			(-2, -2) = -352.3005875
			(1, 1) = 631.6153975
			(-1, -1) = -631.6153975
			(4, 4) = 115.653915
			... skipping 8 entries
		2-Body Terms:
			<sparse integral list with 11 entries>
			(1, 1, 2) = -88.2017421687633
			(4, 4, 2) = 42.40478531359112
			(3, 3, 2) = 2.2874639206341865
			(1, 1, 2, 2) = 4.9425425
			(4, 4, 2, 2) = -4.194299375
			... skipping 6 entries
		3-Body Terms:
			<sparse integral list with 1 entries>
			(4, 3, 2) = 26.25167512727164
	OccupiedModals:
		None

```
Which sums to 25 entries whereas the reference data for the old Watson has 24 entries. While I can correlate the 1 and 2 body terms shown to the test reference value, the 3 body term seems odd. 

### How can we reproduce the issue?

Run the unit test `test/drivers/second_quantization/test_molecule_driver.py`

### What should happen?

Should pass

**Comment by mrossinek** [comment]
Is this not again related to the different Gaussian versions A03 vs. C01 which we had discussed in the past?
They fixed a bug in Gaussian which affected our unittest and I do believe to recall that it was especially affecting the 3-body term.

**Comment by woodsp-ibm** [comment]
> Is this not again related to the different Gaussian versions A03 vs. C01

It might get to that point once the test is working. At present its still coded expecting the now deprecated and removed WatsonHamiltonian as noted above which had the .data field that the test is still looking for.
