### ISSUE TITLE
Disambiguate `num_orbitals`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#64]
### What is the expected enhancement?

@Cryoris brought up the very good suggestion, that we should make an effort to disambiguate the commonly used `num_orbitals` keyword argument. This is used throughout a large part of the stack with either of the two meanings:
1. number of *molecular* orbitals
2. number of *spin* orbitals

Before releasing Nature, we should attempt an effort to clearly disambiguate these cases by replacing the argument with (e.g.)
1. `num_molecular_orbitals`
2. `num_spin_orbitals`

This will clearly tell the user what is expected without having to look into the docstring of each class.

**Comment by woodsp-ibm** [comment]
Yes, agree. Closer to the user problem where the end user was more likely to configure things we had leaned towards allowing them to think etc in MOs. As soon as we get to the operator then its block spin. Arguably MOs is a single number whereas perhaps spin ought to be a tuple, like the num particles, so if that were the case the type would help too, though of course naming is front and center

**Comment by mrossinek** [comment]
Do you mean you would like `num_spin_orbitals` to be a tuple in order to easily differentiate the case of seniority zero or do you see another reason here?

**Comment by woodsp-ibm** [comment]
In the prior FermionicOperator it would be possible to remove say the spin-down orbital but not the corresponding spin-up one so there are more spin up than down orbitals - I do not know if one needs to know, but if one did then a tuple would help ie (num spin up, num spin down). I know we do the particles this way, just wondering about doing it for the spin orbitals too. I do not know how seniority zero affects this other than the orbitals are doubly occupied so I guess this does not really apply in this case so maybe the single number is the only common notion - though with seniority zero I am not sure they are spin orbitals in the way we normally think of them

**Comment by mrossinek** [comment]
> In the prior FermionicOperator it would be possible to remove say the spin-down orbital but not the corresponding spin-up one so there are more spin up than down orbitals

I cannot think of an application where this makes sense physically. Thus, I'd argue that the `int` for the number of orbitals is sufficient. @pbark what do you think?
