### ISSUE TITLE
`ElectronicStructureProblem.get_default_filter_criterion` assumes singlet spin

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#643]
### What is the expected enhancement?

Currently, the `filter_criterion` produced by `ElectronicStructureProblem` assumes a singlet spin configuration without acknowledging this. The default could be improved in this regard. There are at least two approaches to do this:
- measure the number of alpha and beta particles separately
- compare the angular momentum observable with the expected value

The former would require some deeper changes as this will also affect what auxiliary operators need to be generated by the `ParticleNumber` property. The latter is more straight forward but would rely on the `AngularMomentum` property to always be present. This second case will also (to my knowledge) not be able to differentiate particle numbers `(2, 1)` from `(1, 2)`.

**Comment by woodsp-ibm** [comment]
The default filter already assumes it has the AngularMomentum right so comparing with the expected value, that we can determine from the Molecule out of the driver result we should already be able to do better than assume a singlet state right - at least for the ground state as the expectation is that its the ground state of the molecule of the given configuration. 

If these properties end up being more optional from a user perspective then we either filter based on what is measured, and maybe warn its a partial filtering, or error out, a choice I guess.

**Comment by woodsp-ibm** [comment]
> We can even determine it from the difference of the expected number of alpha and beta particles.

True, we rely on this as an output often enough. It should match the multiplicity that was input!

> measure the number of alpha and beta particles separately. What do you think?

It seems like a reasonable improvement around measuring aspects of the state. Back in the day, when these were originally done, we only supported systems with identical alpha and beta numbers. This would end up making ParticleNumber more analogous to the dipole moment I guess. I suppose if you only want the total is there any benefit to only measuring the one operator as is there today, versus two and summing their results afterwards. Are there any complications with symmetry reduction like we have with the dipole if things were to be split.

**Comment by mrossinek** [comment]
> This would end up making ParticleNumber more analogous to the dipole moment I guess.

How so? Because multiple operators would be produced?

> if you only want the total is there any benefit to only measuring the one operator as is there today, versus two and summing their results afterwards

The only benefit would be, that there is one auxiliary operator fewer which needs to be measured. However, thinking ahead into the future where we may want to evaluate the 1- and 2-body reduced density matrices, a single auxiliary operator to measure is not going to cause any overhead. Furthermore, the number of particles can be determined from the 1-RDM once we start doing this.

> Are there any complications with symmetry reduction

You mean with Seniority Zero as in #640? @pbark or @jschuhmac can probably answer this better but I do not think that there are any downsides. In fact, if we were to produce separate operators for each spin species, in the seniority zero case we would simply only produce a single `VibrationalOp` so nothing should change here. Afaik the seniority zero case will only support cases where the number of alpha and beta particles is identical, anyways

**Comment by woodsp-ibm** [comment]
>>   Are there any complications with symmetry reduction

> You mean with Seniority Zero 

No, I meant Z2 symmetry reduction (qubit tapering). As long as both parts also commute with the symmetry after the split - since the molecule may contain differing alpha and beta, i.e. its not symmetric in that aspect, I wondered if we could end up like the dipole in this case where we can have some operators not commuting. There has never been a problem with the whole.

**Comment by mrossinek** [comment]
> No, I meant Z2 symmetry reduction

Oh I see. Yes this would need to be tested. I don't know from the top of my head

**Comment by Anthony-Gandon** [comment]
I'm interested in this one, I'll have a look into it
