### ISSUE TITLE
Performance regression of `FermionicOp.reduce`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-nature#647]
### Environment

- **Qiskit Nature version**: main
- **Python version**:  3.9.12
- **Operating system**: macOS 12.3.1

### What is happening?

`FermionicOp.reduce` of main is significantly slower than that of stable version.
`FermionicOp.normal_ordered` and `FermionicOp.to_normal_order` are slow due to the same reason.

### How can we reproduce the issue?

```python
import random
from timeit import timeit

from qiskit_nature.operators.second_quantization import FermionicOp


def random_op(k, n):
    random.seed(123)
    op = sum(
        (
            FermionicOp("".join(random.choices("+-ENI", k=k)), display_format="dense")
            * random.random()
        )
        for _ in range(n)
    )
    return op


def bench(k, n):
    op = random_op(k, n)
    print(f"{timeit(lambda: op.reduce(), number=1)} sec")

bench(12, 1000)
```

main
```
6.409043849 sec
```

stable (v0.3.2)
```
1.1105954169999999 sec
```

### What should happen?

The method should be as fast as that of the stable version.

### Any suggestions?

I took a performance profile with cProfile. It implies that `FermionicOp.__init__` takes more than 70% of time, especially the following code.
https://github.com/Qiskit/qiskit-nature/blob/286c93e0751b069e3543d88561407e4f297dd9e3/qiskit_nature/operators/second_quantization/fermionic_op.py#L270-L272
This part used be a direct assignment as follows. #607 changed this part into a list comprehension, which is the root cause of the performance regression, I guess.
https://github.com/Qiskit/qiskit-nature/blob/be91c8e9657082d8670fd16fd79d02b565fa9f9c/qiskit_nature/operators/second_quantization/fermionic_op.py#L257

I think we need a fast path to set `_data` without any conversion and internal methods should use the fast path as much as possible.

cprofile graph with main branch
![image](https://user-images.githubusercontent.com/31178928/165312654-bdd03feb-bfc5-4e0c-8df6-46319d8fc9dc.png)

**Comment by mrossinek** [comment]
Closed by #649
