### ISSUE TITLE
Freeze core transformer possibly producing unexpected behaviour?

### ISSUE THREAD

**Issue by Unathi-Skosana** [Qiskit/qiskit-nature#652]
### Environment

- **Qiskit Nature version**: 0.3.2
- **Python version**: 3.8.9
- **Operating system**: MacOS and Linux 

### What is happening?

An instance of  ```FreezeCoreTransformer``` with parameters ```freeze_core=False``` and ```remove_orbitals=None``` is producing unexpected side effects on the computed ground states energies, for a particular instance of ```ElectronicStructureProblem```.  

### How can we reproduce the issue?

Please see [this gist](https://gist.github.com/Unathi-Skosana/47d49f1229000bada0f9b09fa9977e11).

### What should happen?

As far as I can understand, by extrapolation  an instance of ```FreezeCoreTransformer``` with the parameters ```freeze_core=False``` and ```remove_orbitals=None``` respectively should be have the same effect as having no transformer at all, since the "core" orbitals are not  frozen and no further molecular orbitals are removed? If that is the case, then the computed ground state energies for a particular instance of ```ElectronicStructureProblem``` with or without the aforementioned ```FreezeCoreTransformer```  instance should be identical.

**Comment by woodsp-ibm** [comment]
It appears the frozen core is always computed, such that the setting of freeze_core has no effect as far as I can see from the code.
