### ISSUE TITLE
Option "paired_double_excitation" for UCC circuit

### ISSUE THREAD

**Issue by Dran-Z** [Qiskit/qiskit-nature#676]
### Background
One common variation of UCC ansatz is [kUpCCGSD](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.kUpCCGSD.html) ansatz, which is a simplified case of generalized UCCSD ansatz. In kUpCCGSD ansatz, double excitations are limited to paired double excitation, which only considers two electrons (one alpha spin and one beta spin) in a molecule orbital excite to another molecule orbital in pair. Thus, the number of parameters can be reduced compared with the Generalized UCCSD ansatz.
### Expected enhancement
An option for paired double excitation in  ` UCC ` .

**Comment by woodsp-ibm** [comment]
You can already do this by providing your own custom method that computes the excitations. See https://github.com/Qiskit/qiskit-nature/blob/ff222f77f78928a701268732bd1013fa9affc4cd/qiskit_nature/circuit/library/ansatzes/ucc.py#L78-L86

**Comment by Dran-Z** [comment]
> You can already do this by providing your own custom method that computes the excitations. See
> 
> https://github.com/Qiskit/qiskit-nature/blob/ff222f77f78928a701268732bd1013fa9affc4cd/qiskit_nature/circuit/library/ansatzes/ucc.py#L78-L86

Thanks, I didn't even know it. I will close the issue then.

**Comment by mrossinek** [comment]
Besides Steve's suggestion above, there is even a convenience subclass specifically for this ansatz. It is called `PUCCD` (for "paired UCC doubles"): https://qiskit.org/documentation/nature/stubs/qiskit_nature.circuit.library.PUCCD.html
It also takes the keyword argument `generalized=True` which I believe should be exactly what you are looking for :+1:

**Comment by Dran-Z** [comment]
@mrossinek Yes indeed. We can use `` UCC `` to create a single excitation ansatz first, and supplement it with the `` PUCCD `` as the double excitation part. In this way we can construct the kUpCCGSD ansatz without specifying the detailed excitations. Thanks a lot for sharing it!

**Comment by mrossinek** [comment]
The `PUCCD` class also has option to include single excitations: `include_singles=(True, True)`
You specify a tuple because you select the excitations for alpha and beta spins separately
