### ISSUE TITLE
Approximate equality for SecondQuantizedOps

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#715]
### What is the expected enhancement?

Comparing two SecondQuantizedOps for approximate equality is useful for testing. As far as I can tell there is no simple way to do this yet.

**Comment by mrossinek** [comment]
I suggest that this could be implemented via `__eq__` and `equiv` (as seen in Terra e.g.) methods on the new classes proposed in #665 and #669
