### ISSUE TITLE
doc test fails locally

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#734]
### Environment

- **Qiskit Nature version**: 2b18a65ec1af71e6d9c066882afee723e72a8231
- **Python version**: 3.9.7
- **Operating system**: RHEL 8.6

### What is happening?

The local documentation check fails.

### How can we reproduce the issue?

1. Make sure your environment is set up properly by running
```
pip install -r requirements.txt -r requirements-dev.txt -c constraints.txt --upgrade
make clean
```
2. Run `make html`

Result:
```
...
WARNING: Cannot resolve forward reference in type annotations of "qiskit_nature.problems.sampling.protein_folding.ProteinFoldingProblem.interpret": name 'ProteinFoldingResult' is not defined
WARNING: Cannot resolve forward reference in type annotations of "qiskit_nature.problems.sampling.protein_folding.ProteinFoldingProblem.interpret": name 'ProteinFoldingResult' is not defined
...
build finished with problems, 2 warnings.
make: *** [Makefile:70: html] Error 1
```

### What should happen?

The check should pass.

**Comment by mrossinek** [comment]
The documentation generation is working fine on the multiple OSs being tested by the CI. You will need to figure out the difference in your setup to determine what is causing this issue.
I suggest that you inspect the Sphinx package versions and make sure they are up to date.

**Comment by kevinsung** [comment]
>I suggest that you inspect the Sphinx package versions and make sure they are up to date.

I tried to do this using the command
```
pip install -r requirements.txt -r requirements-dev.txt -c constraints.txt --upgrade
```

>The documentation generation is working fine on the multiple OSs being tested by the CI.

True, but we should also try to ensure it works locally on most common platforms.
