### ISSUE TITLE
Documentation copyright needs updating

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#767]
### What is the expected enhancement?

The latest docs are still being given a copyright for last year

> © Copyright 2018, 2021, Qiskit Nature Development Team. 

This is set here as  below and needs updating

https://github.com/Qiskit/qiskit-nature/blob/753cad900dcab7b509371a23f974d4dfcbd42fdf/docs/conf.py#L51

... but maybe we can be update the year in the CI to avoid having to manually adjust this going forwards each year?

(Probably same needs correcting in other apps repos too)

**Comment by manoelmarques** [comment]
Currently the copyright year is only checked when the file changes. It means that a file that never changed in 2022 may have it last year still at 2021 or even before. So the behavior should change to update all files even if they haven't changed ?

Currently calling "make copyright" locally, it will update all the years of the changed files. It was a tiresome to do it manually before if many files had changed. This has been updated in all apps.
