### ISSUE TITLE
Builds qcmatrixio.cpython-xx.so module for many python versions instead of just one

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-nature#778]
### Environment

- **Qiskit Nature version**: faacc94fae6d42d993794c7690db9c96e48e4db5
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.1

### What is happening?

It installs all these modules:
```
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-37m-darwin.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-37m-x86_64-linux-gnu.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-38-darwin.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-38-x86_64-linux-gnu.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio%%PYTHON_EXT_SUFFIX%%-darwin.so
%%PYTHON_SITELIBDIR%%/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio%%PYTHON_EXT_SUFFIX%%-x86_64-linux-gnu.so
```
when only one (for python-3.9) is required.

### How can we reproduce the issue?

regular build

### What should happen?

n/a

### Any suggestions?

n/a

**Comment by yurivict** [comment]
Shared object modules have all sorts of architectures, but there is no architecture that is needed:
```
$ file `find work-py39/stage/ -name "*so"`
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-37m-darwin.so:           Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2e6ec50c525d92fb99faf41453ef563fdc20776d, with debug_info, not stripped
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-39-x86_64-linux-gnu.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a928ab70c4d03ce402314bc2b8ace5fe4bb34557, with debug_info, not stripped
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-39-darwin.so:            Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-38-darwin.so:            Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-37m-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f7f7054928c1a985377fede4212210586e9196a8, with debug_info, not stripped
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-38-x86_64-linux-gnu.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=50117a07cc32a699f0b3c953c9f60064c39c11f8, with debug_info, not stripped
work-py39/stage/usr/local/lib/python3.9/site-packages/qiskit_nature/drivers/second_quantization/gaussiand/gauopen/qcmatrixio.cpython-310-darwin.so:           Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
```

**Comment by woodsp-ibm** [comment]
These are a set of prebuilt python extensions to support interfacing to Gaussian 16 software. The one corresponding to the python version and platform will be used, if it exists, if not you will not be able to use Gaussian 16 software - its commercial software and I know its support on Mac, Windows and some Linux versions. Yes, they are all part of the install pkg but only one will finally be used - it takes up a bit of disk space, but has been done to avoid users generally having to build their own interfacing extension - see https://qiskit.org/documentation/nature/apidocs/qiskit_nature.drivers.second_quantization.gaussiand.html

**Comment by yurivict** [comment]
> [...] if not you will not be able to use Gaussian 16 software [...]

But qiskit-nature is still generally useful w/out access to Gaussian software, is this correct?

**Comment by woodsp-ibm** [comment]
Yes, you can use Nature without Gaussian. That is one of a set of drivers supported - PySCF, PyQuante and PSI4 are the others. They do some classical computation given a molecule which results in data used in Nature. You can choose a driver based on support for the platform and your preference (if you have any). For Gaussian the driver and the python extensions there are just not used. This is often the case even on platforms where Gaussian is supported - the code is there ready to be used but you may never use it. You can do other things, like Lattices in Nature even without such a driver. See Nature Optional installs for further driver info https://qiskit.org/documentation/nature/getting_started.html#optional-installs

**Comment by yurivict** [comment]
Thank you!
