### ISSUE TITLE
Use open source quantum chemistry software instead of Gaussian

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-nature#779]
### What should we add?

Unless there is a compelling reason, please use open source quantum chemistry software for quantum chemistry.

[This](https://wiki.fysik.dtu.dk/ase/) page has a partial list of open source quantum chemistry software.

**Comment by yurivict** [comment]
The answer is [here](https://github.com/Qiskit/qiskit-nature/issues/778#issuecomment-1209886371).

Thank you.

**Comment by woodsp-ibm** [comment]
Nature support various drivers - see https://qiskit.org/documentation/nature/getting_started.html#optional-installs This includes open-source quantum chemistry software too. Ok you closed it just as I was answering, so I'll leave it as-is. Yes, similar answer to your other issue.

**Comment by yurivict** [comment]
@woodsp-ibm 
A quick followup question: You support PyQuante. But PyQuante seems to be dead. The older SourceForge-hosted version requires EOLed Python-2.7 And the newer GitHub-hosted fork https://github.com/rpmuller/pyquante2 seems to be dead as well.

Do you have a recommended fork that is supported?

**Comment by woodsp-ibm** [comment]
Yes, it seems to no longer be actively supported. Like the other drivers its an optional install - it does work still but as you say is not actively maintained. In the early days its pure python version, was the only driver option for Windows platform besides the commercial Gaussian16. Nowadays PSI4 supports Windows so there is that option, though PyQuante has the more direct interface and perhaps is a little easier to use albeit its more limited function. Certainly PSI4 is a much more performant/capable software. The optional install instructions refer to and point at Pyquante2 link you show, I am not aware of any active fork of that code.
