### ISSUE TITLE
Add support for SPSAs `termination_checker` in the `VQEClient`

### ISSUE THREAD

**Issue by cpossel** [Qiskit/qiskit-nature#794]
### What is the expected enhancement?

The `termination_checker` argument was added in terra 0.19 to optimizer SPSA. It works perfectly on local backends and remotely with circuit jobs (without runtime). But when using runtime (e.g. via `VQEClient`) the following message appears:
```
[...]\lib\site-packages\qiskit\providers\ibmq\runtime\utils.py:272: UserWarning: Callable <[...].TerminationChecker object at 0x00000284663AA3A0> is not JSON serializable and will be set to None.
  warnings.warn(f"Callable {obj} is not JSON serializable and will be set to None.")
```

The used `TerminationChecker` is basically the one in the release notes:
```
class TerminationChecker:

    def __init__(self, N : int):
        """
        Callback to terminate optimization when the average decrease over
        the last N data points is smaller than the specified tolerance.
        """
        self.N = N
        self.values = []

    def __call__(self, nfev, parameters, value, stepsize, accepted) -> bool:
        """
        Returns:
            True if the optimization loop should be terminated.
        """
        self.values.append(value)

        if len(self.values) > self.N:
            last_values = self.values[-self.N:]
            pp = np.polyfit(range(self.N), last_values, 1)
            slope = pp[0] / self.N

            if slope > 0:
                return True
        return False
```

Why is this feature enhancement needed:
Almost every optimizer has some built-in termination criteria. Only the most widely used one, SPSA, does not have this feature. The `termination_checker` allows to add this feature manually but is not usable with qiskit runtime. It would save quite a lot of resources on the IBM backends if one could easily terminate the long-running VQE runtime jobs (and other jobs using SPSA) with the `termination_checker`.

As pointed out [here](https://qiskit.slack.com/archives/C02SQUM7YHJ/p1660825319096369?thread_ts=1660813412.394839&cid=C02SQUM7YHJ) a workaround would be to use the `callback` option to examine the intermediate result and cancel the job. But this approach is quite cumbersome...

**Comment by Cryoris** [comment]
Yeah we don't support serializing and sending an arbitrary function, which is essentially what the termination checker is. One solution could be to implement a `TerminationChecker` in Qiskit directly with some frequently used default options (e.g. check gradient norms, loss difference, ...) and then serialize that objects.

But I don't think we can suppport custom termination checkers, since that would mean uploading individual functions. With the new Qiskit Primitives however you should be able to just run SPSA locally, where you can use the termination checker, while still getting the runtime speed.

**Comment by cpossel** [comment]
@Cryoris Do you have a rough estimate for me when the qiskit primitives will be available? In other words, is it worth waiting till then?

I really like to have a `TerminationChecker` for `SPSA`. So I wouldn't mind implementing one myself in qiskit directly.
In that case it would help a lot if someone could point me to a nice source which frequently used default options are useful or discuss it with me.

**Comment by Cryoris** [comment]
> @Cryoris Do you have a rough estimate for me when the qiskit primitives will be available? In other words, is it worth waiting till then?

Now 🙂 

@cpossel I'll go ahead and close this issue, but I'm happy to discuss more or re-open the issue if there's something left to do!
