### ISSUE TITLE
Direct-Mapper (bosonic)

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-nature#8]
Migrated from Enterprise Github.
Creator: @mrossinek

### What is the expected behavior?

Implement and test the `DirectMapper`.
This issue breaks-out of #18 and can be used to assign and discuss related topics.

- [ ] Implementation
- [ ] Unittest
- [ ] Documentation

**Comment by mrossinek** [comment]
Since the `BosonicOp` will not exist in the originally proposed form, the implementation of this mapper will likely coincide with the `LinearMapper` (#7). Therefore, I am closing this as a duplicate thereof.
