### ISSUE TITLE
Finish the QubitConvertor implementation

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-nature#82]
A first pass was merged with Z2Symmetry support, this should be added to the function, along with the two qubit reduction based on the mappers.

If we provide a mechanism to map state from its fermionic to qubit equivalent, as we need for HartreeFock, then this should be added and exposed on the Qubit convertor as a capability too based on the function of state mapping being added to and provided by the mappers. So they would map state as well as operators to the qubit form.

**Comment by ikkoham** [comment]
Just FYI: for two qubit reduction, the converter is implemented [here](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/opflow/converters/two_qubit_reduction.py). This may be useful for your purpose.

**Comment by woodsp-ibm** [comment]
@ikkoham Right thanks. Both the Z2Symmetry and the two qubit reduction are to be implemented based on the work you did to support that in opflow. We just need keywords here to enable that to be called or not as part of the conversion done here.
