### ISSUE TITLE
AttributeError: partially initialized module 'qiskit' has no attribute '_accelerate'... while running tests

### ISSUE THREAD

**Issue by AleksandraLeszczyk** [Qiskit/qiskit-nature#822]
### Environment

- **Qiskit Nature version**: main branch (commit 540550c2a9af08212fcaa9bb6272ff7fca52dfe3)
- **Python version**: 3.8
- **Operating system**: Ubuntu 20.04 LTS

### What is happening?

I want to run tests in the cloned repo, but all tests fail. For most tests, the error is the same, i.e.

```
======================================================================
ERROR: utils.test_linalg (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: utils.test_linalg
Traceback (most recent call last):
  File "/home/ola/miniconda3/envs/qiskit_nature_dev/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/ola/miniconda3/envs/qiskit_nature_dev/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ola/src/qiskit-nature/test/utils/test_linalg.py", line 15, in <module>
    from test import QiskitNatureTestCase
  File "/home/ola/src/qiskit-nature/test/__init__.py", line 15, in <module>
    from .nature_test_case import QiskitNatureTestCase
  File "/home/ola/src/qiskit-nature/test/nature_test_case.py", line 23, in <module>
    from qiskit_nature import settings
  File "/home/ola/src/qiskit-nature/qiskit_nature/__init__.py", line 53, in <module>
    from qiskit.algorithms.minimum_eigen_solvers.minimum_eigen_solver import (
  File "/home/ola/miniconda3/envs/qiskit_nature_dev/lib/python3.8/site-packages/qiskit/__init__.py", line 27, in <module>
    sys.modules["qiskit._accelerate.stochastic_swap"] = qiskit._accelerate.stochastic_swap
AttributeError: partially initialized module 'qiskit' has no attribute '_accelerate' (most likely due to a circular import)

----------------------------------------------------------------------
Ran 213 tests in 0.015s

FAILED (errors=213)
```

### How can we reproduce the issue?

```
>> conda create  -n qiskit_nature_dev python=3.8
>> conda activate qiskit_nature_dev
>> ~/miniconda3/envs/qiskit_nature_dev/bin/pip install -r requirements-dev.txt
>> make test
```

### What should happen?

What can I do to run tests without the AttributeError? Errors appear only while testing, but I can run scripts that use Qiskit and Qiskit Nature modules.

```
>> cat example_running_smoothly.py
from qiskit import QuantumCircuit
from qiskit_nature.drivers.second_quantization import FCIDumpDriver
print("success")
>> python example_running_smoothly.py
success
>>
```

The error seems to be similar to [this issue ](https://github.com/Qiskit/qiskit/issues/811), but I don't find such a name conflict.

**Comment by mrossinek** [comment]
This is an error resulting from an incorrect (or entirely missing) installation of https://github.com/Qiskit/qiskit-terra/.
As outlined in the [installation instructions](https://qiskit.org/documentation/nature/getting_started.html#installation) under the `Install from source` section, you also need to run `pip install .` (or `pip install -e .`) after having installed the development requirements. Without that step, the actual runtime requirements are not installed. If your issues persist after installing Qiskit Terra, please take consider filing an issue report there.

**Comment by AleksandraLeszczyk** [comment]
Thank you, @mrossinek, for advising to install not only `qiskit_nature` but also other `qiskit` modules from the source. It helped me to understand the `qiskit` development better. However, it didn't cure the problem with imports. I found a solution, and I hope it might help someone in the future.

The problem was caused by `qiskit-nature/test/random.py` file, which overwrote the standard python library `random` and caused problems with circular imports. I changed a name of a file to `qiskit_tmp_random.py` and updated dependencies in `qiskit-nature/test/`. Now, the tests are working well.

**Comment by manoelmarques** [comment]
The problem exists when using:
```
python -m unittest discover -v test
```
It doesn't happen if you use:
```
stestr --test-path test run
```
Probably due to how both tools load the libraries.
It is a bug and the solution from @AleksandraLeszczyk  works. Thank you for pointing this out. We will open a PR fixing it.
