### ISSUE TITLE
register length should be determined at map time instead of initialization

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#831]
### What is the expected enhancement?

Currently, `SparseLabelOp.register_length` stores the "register length" of the operator. Typically this would be the number of qubits in the operator when it is mapped to qubits. However, as far as I can tell, there is no need to store the register length with the original operator. Instead, the register length can be specified at the time the operator is mapped to qubits. For example,
```python
qubit_op = JordanWigner().map(fermionic_op, register_length=5)
```
If the register length is not specified, it can be automatically inferred from the indices present in the operator. This approach is more flexible because the user would not need to specify a register length during initialization.

**Comment by mrossinek** [comment]
I don't think it makes sense to specify this as an input to the mapper. Instead, the user could just set the `fermionic_op.register_length` attribute to the desired value before passing it into the mapper.

Many scenarios (e.g. when comping from a set of integrals/coefficients for a Hamiltonian) will have a fixed `register_length` to begin with. In those cases it would be good to be able to guard against user error resulting from an incorrect value.
However, I agree that this will be a useful feature and ease the use of the operator classes. As the `SparseLabelOp` is currently designed to be immutable, this will need a little design discussion.

**Comment by kevinsung** [comment]
>I don't think it makes sense to specify this as an input to the mapper. Instead, the user could just set the fermionic_op.register_length attribute to the desired value before passing it into the mapper.

I guess whether something "makes sense" is subjective. I think this is mostly a question of which of the following APIs are preferable:
```python
qubit_op = JordanWigner().map(fermionic_op, register_length=5)
```
versus
```python
fermionic_op.register_length = 5
qubit_op = JordanWigner().map(fermionic_op)
```

I much prefer the first one. It is much easier to document and discover because the documentation must live with function itself, and the argument can be discovered by tab auto-completion in an IDE. The second method would require one to know ahead of time about the existence of the `register_length` property and the way it is handled by the mapper. Furthermore, the first method is much more readable because all of the logic is contained in one statement rather than split between two statements. For example, it is not clear from inspection that the line
```python
fermionic_op.register_length = 5
```
should have an effect on the line
```
qubit_op = JordanWigner().map(fermionic_op)
```
One could imagine a situation where these lines of code are written together, then at a later point of time some code is added between these lines. The readability would suffer greatly.

**Comment by mrossinek** [comment]
I see your points. At this point, I would prefer a more explicit argument like `num_qubits` if we were to add it to the `QubitMapper` and `QubitConverter` interfaces. `register_length` is a naming convention which we chose, since the length of the second-quantized operators does not necessarily equal the number of qubits. But in this setting, that's precisely what you are targeting.

Questions would arise, as to how such an API change would combine with the `two_qubit_reduction` and general Z2 symmetry reductions. Users might be confused when specifically requesting a given length only to find a shorter qubit operator being returned due to the encountered symmetries..
