### ISSUE TITLE
Make initial states a `BlueprintCircuit`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#881]
### What is the expected enhancement?

The ansatze like `UCC` and alike have been implemented as `BlueprintCircuit` which allows "lazy" attribute setting to complete the circuit definition as used for example in the `VQEUCCFactory`.
The same could be done for the initial states like `HartreeFock` and `VSCF`.

**Comment by Unathi-Skosana** [comment]
Hi @mrossinek, I'd like to work on this.
