### ISSUE TITLE
FermionicOp `normal_ordered` and `simplify` should commute

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#888]
### What is the expected enhancement?

It is surprising that simplifying a normal-ordered operator changes it so that it is no longer normal-ordered. Simplification should conserve normal order. The code below should not raise AssertionError.

```python
from qiskit_nature.second_q.operators import FermionicOp

op = FermionicOp({"+_1 -_0": -1})
assert op.simplify().normal_ordered() == op.normal_ordered().simplify()
```

**Comment by mrossinek** [comment]
The more fundamental suggestion here, is that the `.simplify()` operation should preserve the order of the terms and not reorder them based on the term indices.

**Comment by mrossinek** [comment]
There was even a unittest trying to catch this, but it did not:
https://github.com/Qiskit/qiskit-nature/blob/ba3a191b30606d6c1da5c378de2eea7bceaeab57/test/second_q/operators/test_fermionic_op.py#L153-L156
