### ISSUE TITLE
Implement an equivalent to legacy `succ_full` option

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#91]
### What is the expected enhancement?

The [legacy `UCCSD`](https://github.com/Qiskit/qiskit-aqua/blob/main/qiskit/chemistry/components/variational_forms/uccsd.py) implementation had a `method_doubles="succ_full"` option which is not yet implemented in Qiskit Nature.
This option is a variant of the (now named) `SUCCD` option which also includes symmetrically mirrored double excitations, however, using the same parameter as the symmetric counter part (as also noted [here](https://github.com/Qiskit/qiskit-nature/blob/aae9c01b4d02bf5dbaa342c757be2cfef60a31d5/qiskit_nature/circuit/library/ansatzes/succd.py#L34-L35)).

The original implementation in Qiskit Aqua came from the work of [this paper](https://aip.scitation.org/doi/10.1063/1.5141835) in which sections II.E.2 and appendix E provide more in-depth information.
The following Qiskit Nature snippet shows the current state of the `SUCCD` ansatz for the example discussed the aforementioned paper's appendix:
```python
from qiskit_nature.circuit.library.ansatzes import SUCCD
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.mappers.second_quantization import JordanWignerMapper

converter = QubitConverter(JordanWignerMapper())
ansatz = SUCCD(converter, (1, 1), 6)

print(ansatz.decompose().draw())
print(ansatz.excitation_list)
```
which outputs:
```
     ┌─────────────────────────────────────────────────────────────────────────────────────────────┐»
q_0: ┤0                                                                                            ├»
     │                                                                                             │»
q_1: ┤1                                                                                            ├»
     │                                                                                             │»
q_2: ┤2                                                                                            ├»
     │  exp(-it (IYYIXY + IXXIXY + IXYIYY + IYXIYY + IXYIXX + IYXIXX + IYYIYX + IXXIYX))(1.0*t[0]) │»
q_3: ┤3                                                                                            ├»
     │                                                                                             │»
q_4: ┤4                                                                                            ├»
     │                                                                                             │»
q_5: ┤5                                                                                            ├»
     └─────────────────────────────────────────────────────────────────────────────────────────────┘»
«     ┌─────────────────────────────────────────────────────────────────────────────────────────────┐»
«q_0: ┤0                                                                                            ├»
«     │                                                                                             │»
«q_1: ┤1                                                                                            ├»
«     │                                                                                             │»
«q_2: ┤2                                                                                            ├»
«     │  exp(-it (YZYIXY + XZXIXY + XZYIYY + YZXIYY + XZYIXX + YZXIXX + YZYIYX + XZXIYX))(1.0*t[1]) │»
«q_3: ┤3                                                                                            ├»
«     │                                                                                             │»
«q_4: ┤4                                                                                            ├»
«     │                                                                                             │»
«q_5: ┤5                                                                                            ├»
«     └─────────────────────────────────────────────────────────────────────────────────────────────┘»
«     ┌─────────────────────────────────────────────────────────────────────────────────────────────┐
«q_0: ┤0                                                                                            ├
«     │                                                                                             │
«q_1: ┤1                                                                                            ├
«     │                                                                                             │
«q_2: ┤2                                                                                            ├
«     │  exp(-it (YZYXZY + XZXXZY + XZYYZY + YZXYZY + XZYXZX + YZXXZX + YZYYZX + XZXYZX))(1.0*t[2]) │
«q_3: ┤3                                                                                            ├
«     │                                                                                             │
«q_4: ┤4                                                                                            ├
«     │                                                                                             │
«q_5: ┤5                                                                                            ├
«     └─────────────────────────────────────────────────────────────────────────────────────────────┘
[((0, 3), (1, 4)), ((0, 3), (1, 5)), ((0, 3), (2, 5))]
```

In this context, the goal of this issue is to implement a variant of `SUCCD` (or an additional keyword argument to its constructor) which results in the inclusion of the `((0, 3), (2, 4))` excitation, while at the same time still using only three parameters (namely `t[0]-t[2]` in the example above). This should be achieved by ensuring that `((0, 3), (1, 5))` and `((0, 3), (2, 4))` are assigned the same parameter (namely `t[1]` in the example above).

**Comment by Dran-Z** [comment]
If no one has tried by far, I would like to shoot an attempt at it.

**Comment by mrossinek** [comment]
> If no one has tried by far, I would like to shoot an attempt at it.

Sure go ahead :+1:

**Comment by Dran-Z** [comment]
> @Dran-Z if you want to work on this as part of unitary hack, please remember to register for the event (making you eligible for the bounty) and open a draft PR as soon as possible 👍 For more information, please refer to: https://unitaryhack.dev/

@mrossinek Thanks for the reminder. I checked the code and believe I have a workflow pipeline in my mind. The modification involves how to pass the parameters up to its parent class `UCC`. The work can be divided in two steps: 1. Get the excitation list and pair the symmetric excitations together. 2. Pass each two symmetric excitations as one operator(maybe this is the easiest way) up. 

I think I still need some time to figure out the relation between `EvolvedOperatorAnsatz`, `UCC` and `SUCCD`. I don't think I am now aiming at getting the bounty because I have another deadline by this week(But anyone else interested can still aim at this cash bounty). If not, I will still keep working on this problem later.

**Comment by YuNariai** [comment]
I think I figured this out, may I make a pull request?

**Comment by Dran-Z** [comment]
> I think I figured this out, may I make a pull request?
Sure just do it if you figured it out.
