### ISSUE TITLE
Support interleaved qubit ordering

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#918]
### What should we add?

Currently, all methods which map from spin orbitals to qubits assume a block-ordered arrangement of the qubit register. That means that the first half of the qubits encodes the alpha- and second half the beta-spin orbitals.

It can make sense to specifically want to use an _interleaved_ ordering where odd indices encode alpha- and even indices encode the beta-spin registers. Supporting this via a global configuration setting would be ideal since this can ensure consistent behavior across the various components affected by this (mappers, circuits, etc.)

Alternatively, it may be possible to centralize this configuration via the mappers (since our initial state and ansatz circuits also use mappers). If doing this, the 2-qubit reduction in the case of the `ParityMapper` would also need to be able to handle this, giving another argument for extracting this qubit reduction functionality out of Terra and back into Nature (see also [this comment](https://github.com/Qiskit/qiskit-nature/issues/879#issuecomment-1278531697)).

**Comment by jlapeyre** [comment]
Julia code for doing this is in [this file](https://github.com/Qiskit-Extensions/ElectronicStructure.jl/blob/7a78c0449015a9736216a1446e5ad4ac9e617c05/src/interaction_operator.jl#L91-L110). I may also have python code for this, but I am unable to find it at the moment.

**Comment by mrossinek** [comment]
I think that indeed the last suggestion in the issue description seems like the most feasible approach for this. Especially now that `QubitMapper` objects can be used by themselves (i.e. without being wrapped into a `QubitConverter`; see also #967). On top of that, the planned `TaperedQubitMapper` (see #974) already proposes the idea of a "wrapped mapper" in the sense that any mapper can be taken and wrapped to apply the tapering as a secondary step.
This kind of "mapper chaining" could also be used to implement an interleaved ordering, for example along the lines of this:

```python
class InterleavedMapper:

    def __init__(self, mapper: QubitMapper):
        self.mapper = mapper
        
    def map(self, operator: SparseLabelOp) -> SparsePauliOp:
        block_ordered_op = self.mapper.map(operator)
        
        # perform operations to convert the block-ordered qubit operator into interleaved
        # maybe Terra has some utilities for qubit-reordering?
        # Otherwise some sort of string-translation could be used
        interleaved_op = ...
        
        return interleaved_op
```

This would allow seamless integration into the existing workflow.
Furthermore, this automatically deals with cases like our classically-inspired ansatze (UCC, UVCC) since these first build second-quantized operators and then subsequently map them into qubit space, before evolving them to yield the actual QuantumCircuit building blocks.
