### ISSUE TITLE
Improve `FCIDump` parser

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#933]
### What is the expected enhancement?

Our current implementation of the `FCIDump` parser runs into **serious** bottlenecks for larger systems. This is mostly due to the fact of how we are dealing with loading the permutational symmetries. Instead of tracking the index tuples which we encounter and later on populating the symmetric variations, we construct the full list of potential index tuples ahead of time, and then "cross off" the ones that we did indeed find. Considering that the index tuples scale as `N^4`, this is obviously horrendously expensive for large `N`.

This issue suggests that the implementation be revisited and improved as to remove said bottleneck :+1:

**Comment by lucarighetti3** [comment]
I would be happy to work on this!
