### ISSUE TITLE
Implement a `BosonicOperator`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#958]
### What should we add?

In order to enable the addition of #557 as well as the implementation of the `BoseHubbardModel`, we need to implement a `BosonicOperator`. The expectation for this class is fairly straight forward:

- it supports the creation (`+`) and annihilation (`-`) operations
- it has bosonic commutation rules (contrary to the `FermionicOperator`s anti-commutation)

Some observations:
- this class differs from the `VibrationalOp` because it does not introduce the notion of modals and only operated on entire modes all at once
- this class differs from the `SpinOp` because it supports a different alphabet of operators and because its mappers will need to work fundamentally differently (see below)

In order for this class to be useful, the implementation of it should also provide a mapper which enables the `BosonicOperator -> SparsePauliOp` translation. The naming of this class will need to be discussed since I am assuming the initial mapper will be the equivalent to the direct/linear mapper which we have for the `VibratonalOp` and `SpinOp`, resp.

The linear mapper will need to implement the following:
$$b^\dagger_k \rightarrow \sum_{n_k=0}^{n_k^{max}-1} \sqrt{n_k+1} \sigma_{n_k}^+ \sigma_{n_k+1}^-$$
(see also Section II.C in [Miessen et al.](https://arxiv.org/abs/2108.04258)).

Here, $n_k^{max}$ determines the truncation order for each bosonic mode which can be interpreted in a similar style to the _spin_ in our `SpinOp`. Initially, having a fixed truncation order for the `BosonicOp` will be sufficient but in the future we may want our operator and mappers to support different truncation orders for each bosonic mode (identical to #515).

In summary, the `BosonicOp` will:
- differ from `SpinOp` because it implements a different operational alphabet and must be mapped to the qubit space differently
- differ from `VibrationalOp` because the expansion of the bosonic modes with a given truncation happens during the mapping process to the qubit space in contrast to the expansion into second quantization in the case of the `VibrationalOp` which is necessary because its basis may incur different coefficients for different "modals"

<hr/>

The technical requirements to close this issue are:
- [ ] a working `BosonicOp` largely similar to the existing `FermionicOp`
- [ ] a `LinearMapper` (either `BosonicLinearMapper` or overloading the existing `LinearMapper` to support both, `SpinOp` and `BosonicOp`) implementing the mapping outlined above

Since the `BosonicOp` is basically useless without the mapper, both of these tasks should be implemented in the same PR.

**Comment by ftroisi** [comment]
To be explicit about the annihilation operator, it has the following mapping:

$$\hat{b}_{k} = \sum_{n_k = 0}^{n_k^{max} - 1} \sqrt{n_k + 1} \sigma_{n_k}^- \sigma_{n_k + 1}^+$$
