### ISSUE TITLE
Implement a `TaperedQubitMapper`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#974]
### What should we add?

As the third step of #967 we should implement a `TaperedQubitMapper` which gathers all the `Z2Symmetries`-related tapering techniques currently controlled via the `QubitConverter` in a single `QubitMapper` wrapper:

```python
class TaperedQubitMapper:
    def __init__(self, mapper: QubitMapper, z2symmetries: list[int]):
        ...
        
    @classmethod
    def from_problem(cls, mapper: QubitMapper, problem: ElectronicStructureProblem):
        # implies the previous z2symmetries == "auto" case
        # extract problem.hamiltonian and problem.symmetry_sector_locator
        
    def map(self):
        # uses self.mapper.map + applies tapering
        
    # provide 2-step tapering i.e. one method for _only_ mapping and one to apply tapering on-top
    # this is necessary for cases like the HF bitstring and qEOM
```

Just like with my proposal in #973, this mapper will be stateful.

<hr/>

This is blocked by https://github.com/Qiskit/qiskit-terra/issues/9140

**Comment by Anthony-Gandon** [comment]
- [ ] Once we work on that mapper we need to think about how to handle the suppress_none=False case
which we had in the QubitConverter.
