### ISSUE TITLE
Question: How to correctly rewrite an example Cirq code in Qiskit?

### ISSUE THREAD

**Issue by MartinBeseda** [Qiskit/qiskit-nature#982]
Hello,
first of all, I'm not sure, if this is the right place to ask this question, so if it isn't, I'm sorry.

I need to rewrite some more complex code from Cirq to Qiskit and having no previous experience with Cirq, I'm a little puzzled by the situation. 

I know, that since Qiskit Nature v0.6 it's planned to support an interleaved ordering of spin-orbitals (issue #918), but currently I don't see the mistakes in my attempt.

The Cirq code looks like this:
```
import cirq
import numpy as np
import openfermion as of
import sympy

H = of.FermionOperator('0^ 2', 1) + of.FermionOperator('0 1^', 1) + of.FermionOperator('0^ 1 2^ 3^', 0.9) \
    + of.FermionOperator('0^ 1 2 3', -0.1)

H = of.FermionOperator('0^ 1', 1) + of.FermionOperator('0 2^', 1) + of.FermionOperator('0^ 2 1^ 3^', 0.9) \
    + of.FermionOperator('0^ 2 1 3', -0.1)

Hmat = of.get_sparse_operator(H, n_qubits=4).A

print(H)
print(sorted(np.linalg.eig(Hmat)[0]))

circuit = cirq.Circuit()
qubits = cirq.LineQubit.range(4)

alpha = sympy.Symbol('alpha')
beta = sympy.Symbol('beta')
gamma = sympy.Symbol('gamma')
delta = sympy.Symbol('delta')

circuit.append(cirq.ry(alpha).on(qubits[0]))
circuit.append(cirq.ry(beta).on(qubits[1]))
circuit.append(cirq.ry(gamma).on(qubits[2]))
circuit.append(cirq.ry(delta).on(qubits[3]))
circuit.append(cirq.X(qubits[2]).controlled_by(qubits[0]))

full_circ = cirq.resolve_parameters(circuit, {'alpha': 1, 'beta': 1, 'gamma': 1, 'delta': 1})
sv = full_circ.final_state_vector()

print(sv)
print(sv.conj().T @ Hmat @ sv)
```

This Cirq code is giving the following output:

```
1.0 [0 2^] +
1 [0^ 1] +
-0.1 [0^ 2 1 3] +
0.9 [0^ 2 1^ 3^]
[(-0.547722557505166+5.551115123125783e-17j), (-7.994927024450326e-17-0.5477225575051663j), 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, (4.85722573273506e-17+0.5477225575051662j), (0.5477225575051663+0j)]
[0.5931328 +0.j 0.32402992+0.j 0.32402992+0.j 0.17701835+0.j
 0.32402992+0.j 0.17701835+0.j 0.17701835+0.j 0.09670557+0.j
 0.17701835+0.j 0.09670557+0.j 0.32402992+0.j 0.17701835+0.j
 0.09670557+0.j 0.05283049+0.j 0.17701835+0.j 0.09670557+0.j]
(0.11040049624731614+0j)
```

I'd like to be able to rewrite this example into an equivalent code in Qiskit, where, as I'm aware is a different spin-orbital mapping, so that I switched 1st and 2nd qubits in ansatz. The code looks like this:

```
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.quantum_info import Statevector
from qiskit_nature.operators.second_quantization import FermionicOp
import numpy as np

H = FermionicOp([('+_0 -_2', 1), ('-_0 +_1', 1), ('+_0 -_1 +_2 +_3', 0.9), ('+_0 -_1 -_2 -_3', -0.1)], register_length=4)


print(H)
print(sorted(np.linalg.eig(H.to_matrix().A)[0]))

ansatz = QuantumCircuit(4)
p = ParameterVector('theta', length=4)
for i, q in enumerate(ansatz.qubits):
    ansatz.ry(p[i], q)
ansatz.cx(0, 1)

params = [1]*4

vecA = Statevector(ansatz.bind_parameters(params)).data

print(vecA)
print((vecA.conj().T @ H.to_matrix() @ vecA).real)
```

But the output is different:

```
Fermionic Operator
register length=4, number terms=4
  (1+0j) * ( +_0 -_2 )
+ (1+0j) * ( -_0 +_1 )
+ (0.9+0j) * ( +_0 -_1 +_2 +_3 )
+ (-0.1+0j) * ( +_0 -_1 -_2 -_3 )
[(-0.547722557505166+5.551115123125783e-17j), (-7.997636868137208e-17-0.5477225575051663j), 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, (4.85722573273506e-17+0.5477225575051662j), (0.5477225575051663+0j)]
[0.5931328 +0.j 0.17701835+0.j 0.32402992+0.j 0.32402992+0.j
 0.32402992+0.j 0.09670557+0.j 0.17701835+0.j 0.17701835+0.j
 0.32402992+0.j 0.09670557+0.j 0.17701835+0.j 0.17701835+0.j
 0.17701835+0.j 0.05283049+0.j 0.09670557+0.j 0.09670557+0.j]
-0.02401568533842704
```

Why are the expectation values different? Is the operator rewritten in an incorrect way or does the ansatz need different treatment, when rewritten to Qiskit?

Thank you very much for all your help!

P.s.: If you don't want to keep the question here, I also asked at [Quantum Computing SE](https://quantumcomputing.stackexchange.com/questions/29113/how-to-rewrite-this-cirq-problem-into-qiskit).

**Comment by mrossinek** [comment]
I think you will have better chances at an answer on stackexchange. I do not have much prior experience with cirq but I will try nonetheless to give you some pointers.

The biggest thing seems to be that your are mistranslating the Hamiltonian. Not necessarily because of the qubit ordering but because of the string translation: `2^` should be `+_2` but you are mapping it to `-_2` (as an example).

Another thing is that the `FermionicOp.to_matrix()` method has a very specific ordering. I am not sure whether this matches how Cirq is creating a matrix so I would suggest that you compare those matrices directly.

Hopefully this helps. I'm closing this for now, but feel free to follow-up if you need Qiskit Nature-specific help :+1:
