### ISSUE TITLE
07_leveraging_qiskit_runtime.ipynb-Errors

### ISSUE THREAD

**Issue by fizixmastr** [Qiskit/qiskit-nature#990]
### Environment

- **Qiskit Nature version**: 0.5.1
- **Python version**: 3.10
- **Operating system**: Linux Ubuntu 22.04.1

### What is happening?

Multiple issues prevent the example code from running.

In the second block,
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [11], line 18
     14 print(particle_number)
     16 # specify active space transformation
     17 active_space_trafo = ActiveSpaceTransformer(
---> 18     num_electrons=particle_number.num_particles, num_molecular_orbitals=3
     19 )
     21 # transform the electronic structure problem
     22 problem = active_space_trafo.transform(problem)

AttributeError: 'ParticleNumber' object has no attribute 'num_particles'
```

I believe this value should be 2, but I cannot trace where the issue arises. Adjusting this to a number allows the next error to be

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [14], line 17
     14 print(particle_number)
     16 # specify active space transformation
---> 17 active_space_trafo = ActiveSpaceTransformer(
     18     num_electrons=2, num_molecular_orbitals=3
     19 )
     21 # transform the electronic structure problem
     22 problem = active_space_trafo.transform(problem)

TypeError: ActiveSpaceTransformer.__init__() got an unexpected keyword argument 'num_molecular_orbitals'
```

Looking at the `ActiveSpaceTransformer()` definition, I think this should be corrected to `num_spatial_orbitals`?

While I cannot be sure that I have set the problem correctly because it relies on these two assumptions, I believe that the next error is unrelated.

In block 4 the target energy cannot be found because eigenenergies is no longer an attribute of  `ElectronicStructureResult`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [18], line 3
      1 import numpy as np
----> 3 target_energy = np.real(np_result.eigenenergies + np_result.nuclear_repulsion_energy)[0]
      4 print("Energy:", target_energy)

AttributeError: 'ElectronicStructureResult' object has no attribute 'eigenenergies'
```

Changing this to `np_result.total_energies`  gives nearly the same result as in the example.

A similar issue/error/fix happens in block 8

Block 11 creates a long winded error that I think is related to deprecation of passing the optimizer as a dict. I have changed this to the `optimizer = SPSA(maxiter=100)` and now the code attempts to execute, but fails with a new issue that I cannot say for sure is a result of the other corrections I have made.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [39], line 2
      1 runtime_vqe_groundstate_solver = GroundStateEigensolver(qubit_converter, runtime_vqe)
----> 2 runtime_vqe_result = runtime_vqe_groundstate_solver.solve(problem)

File ~/programs/miniconda3/envs/qu_venv/lib/python3.10/site-packages/qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py:81, in GroundStateEigensolver.solve(self, problem, aux_operators)
     76 main_operator, aux_ops = self.get_qubit_operators(problem, aux_operators)
     77 raw_mes_result = self.solver.compute_minimum_eigenvalue(  # type: ignore
     78     main_operator, aux_ops
     79 )
---> 81 eigenstate_result = EigenstateResult.from_result(raw_mes_result)
     82 result = problem.interpret(eigenstate_result)
     83 return result

File ~/programs/miniconda3/envs/qu_venv/lib/python3.10/site-packages/qiskit_nature/second_q/problems/eigenstate_result.py:93, in EigenstateResult.from_result(cls, raw_result)
     91 if isinstance(raw_result, MinimumEigensolverResult):
     92     return EigenstateResult.from_minimum_eigensolver_result(raw_result)
---> 93 raise TypeError(
     94     f"Cannot construct an EigenstateResult from a result of type, {type(raw_result)}."
     95 )

TypeError: Cannot construct an EigenstateResult from a result of type, <class 'qiskit_nature.runtime.vqe_client.VQERuntimeResult'>.
```

### How can we reproduce the issue?

Running the code with up-to-date packages will likely cause all of the errors I have listed above.

### What should happen?

Especially as this is a tutorial, I would suggest that it should run with only changing the provider and backend.

### Any suggestions?

I have given some recommendations above, but I don't yet know the best ways to correct these issues as the tutorial still fails to execute.

**Comment by mrossinek** [comment]
Thank you for pointing this out to us! This tutorial cannot be run by our CI because of its connection to the runtime service. Thus, this went unnoticed.

It looks like I updated it as part of #796 but overlooked updating it as part of the subsequent refactoring steps like #841.

**Comment by parxivaal** [comment]
The TypeError Issue is still there, it's not fixed yet.

**Comment by mrossinek** [comment]
> The TypeError Issue is still there, it's not fixed yet. One where you cannot construct the EigenstateResult.

It is all working correctly on my end. Please make sure that you have the latest version of the tutorial downloaded (compare with [here](https://qiskit.org/documentation/nature/tutorials/07_leveraging_qiskit_runtime.html) and [here](https://github.com/Qiskit/qiskit-nature/blob/69ed104de80f0b5e7235f6d59894e0b13eead735/docs/tutorials/07_leveraging_qiskit_runtime.ipynb)).
When running this, pay attention to the requirements listed in the notebook: Qiskit Terra 0.22.0 and Qiskit Nature 0.5.0 as the minimum required versions.
